# Generated by Django 4.2.7 on 2026-03-16 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
        ('project_manager_agent', '0001_initial_pm_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('overdue_task', 'Overdue Task'), ('blocked_task', 'Blocked Task'), ('unassigned_high_priority', 'Unassigned High Priority'), ('deadline_approaching', 'Deadline Approaching'), ('workload_imbalance', 'Workload Imbalance'), ('project_at_risk', 'Project At Risk'), ('member_inactive', 'Member Inactive'), ('milestone_due', 'Milestone Due'), ('sprint_overloaded', 'Sprint Overloaded'), ('custom', 'Custom')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, help_text='Extra data (task IDs, user IDs, etc.)', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_notifications', to='core.companyuser')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_notifications', to='core.project')),
            ],
            options={
                'verbose_name': 'PM Notification',
                'verbose_name_plural': 'PM Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
