# Generated by Django 4.2.7 on 2026-03-26 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
        ('project_manager_agent', '0002_pmnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('proposed_time', models.DateTimeField(help_text='Currently proposed meeting time')),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('counter_proposed', 'Counter Proposed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(help_text='Company user invited to the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='invited_scheduled_meetings', to='core.companyuser')),
                ('organizer', models.ForeignKey(help_text='Company user who scheduled the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='organized_scheduled_meetings', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Scheduled Meeting',
                'verbose_name_plural': 'Scheduled Meetings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('counter_proposed', 'Counter Proposed'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('proposed_time', models.DateTimeField(blank=True, help_text='New proposed time (for counter-proposals)', null=True)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for rejection or counter-proposal')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='project_manager_agent.scheduledmeeting')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_responses', to='core.companyuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
