# Generated by Django 4.2.7 on 2026-03-30 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager_agent', '0003_scheduledmeeting_meetingresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingresponse',
            name='responder',
        ),
        migrations.AddField(
            model_name='meetingresponse',
            name='responded_by',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('invitee', 'Invitee')], default='organizer', help_text='Who responded: organizer (CompanyUser) or invitee (project User)', max_length=20),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='invitee',
            field=models.ForeignKey(help_text='Project user (Django User) invited to the meeting', on_delete=django.db.models.deletion.CASCADE, related_name='invited_scheduled_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
