# Generated by Django 4.2.7 on 2026-04-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager_agent', '0005_add_meeting_scheduler_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='invitee',
            field=models.ForeignKey(blank=True, help_text='Primary invitee (legacy). Use participants for multi-user meetings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_scheduled_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially Accepted'), ('rejected', 'Rejected'), ('counter_proposed', 'Counter Proposed'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('counter_proposed', 'Counter Proposed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Reason for rejection or counter-proposal')),
                ('counter_proposed_time', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='project_manager_agent.scheduledmeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
