# Generated by Django 4.2.7 on 2026-04-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0006_add_meeting_participant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='parent_meeting',
            field=models.ForeignKey(blank=True, help_text='Parent meeting for recurring series. Null = standalone or parent itself.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='project_manager_agent.scheduledmeeting'),
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekly_weekdays', 'Weekdays (Mon-Fri)'), ('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Stop recurring after this date', null=True),
        ),
    ]
