# Generated by Django 4.2.7 on 2026-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0007_add_recurring_meeting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='agenda',
            field=models.JSONField(blank=True, help_text='Structured agenda items: [{"item": "...", "done": false}]', null=True),
        ),
    ]
