# Generated by Django 4.2.7 on 2026-04-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0008_add_meeting_agenda_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Actual meeting duration (filled after meeting ends)', null=True),
        ),
    ]
