# Generated by Django 4.2.7 on 2026-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0009_add_actual_duration_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pmknowledgeqachat',
            index=models.Index(fields=['company_user', '-updated_at'], name='project_man_company_81ac4a_idx'),
        ),
        migrations.AddIndex(
            model_name='pmmeetingschedulerchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='project_man_company_fb050e_idx'),
        ),
        migrations.AddIndex(
            model_name='pmnotification',
            index=models.Index(fields=['company_user', 'is_read', '-created_at'], name='project_man_company_72c46f_idx'),
        ),
        migrations.AddIndex(
            model_name='pmprojectpilotchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='project_man_company_487499_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmeeting',
            index=models.Index(fields=['organizer', '-created_at'], name='project_man_organiz_b54bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmeeting',
            index=models.Index(fields=['status', 'proposed_time'], name='project_man_status_9a6c94_idx'),
        ),
    ]
