# Generated by Django 4.2.7 on 2026-04-15 04:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260408_1204'),
        ('project_manager_agent', '0010_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_accepted', 'Meeting Accepted'), ('meeting_rejected', 'Meeting Rejected'), ('meeting_withdrawn', 'Meeting Withdrawn'), ('meeting_rescheduled', 'Meeting Rescheduled'), ('subtasks_generated', 'Subtasks Generated'), ('priority_updated', 'Priority Updated')], max_length=50)),
                ('model_name', models.CharField(help_text='e.g., Project, Task, ScheduledMeeting', max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, help_text='Additional context', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_audit_logs', to='core.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_user', '-created_at'], name='project_man_company_3d2673_idx')],
            },
        ),
    ]
