# Generated by Django 5.2.13 on 2026-06-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0011_add_audit_log_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='timezone_name',
            field=models.CharField(default='UTC', help_text='IANA timezone the proposed_time was set in. Reminders + emails render local time using this.', max_length=64),
        ),
    ]
