# Generated by Django 5.2.13 on 2026-06-03 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_task_recurrence'),
        ('project_manager_agent', '0012_meeting_timezone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMNotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label, e.g. "#pm-alerts" or "PM Lead Email"', max_length=120)),
                ('channel_type', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('email', 'Email (extra recipient)')], max_length=20)),
                ('target', models.CharField(help_text='Webhook URL for slack/teams, or email address for email channels.', max_length=512)),
                ('severities', models.CharField(default='info,warning,critical', help_text='Comma-separated subset of severities to forward (info,warning,critical).', max_length=64)),
                ('types', models.CharField(blank=True, default='', help_text='Optional comma-separated subset of notification_types to forward. Empty = all.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_notification_channels', to='core.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='The PMNotification.notification_type this template applies to.', max_length=50)),
                ('name', models.CharField(help_text='Internal label for this template.', max_length=120)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('default_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_notification_templates', to='core.company')),
            ],
            options={
                'ordering': ['notification_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'notification_type', 'name'), name='uniq_company_type_name')],
            },
        ),
    ]
