# Generated by Django 4.2.10 on 2026-07-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0014_project_pilot_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectpilotjob',
            new_name='project_man_company_4041b1_idx',
            old_name='ppilot_job_cu_created_idx',
        ),
        migrations.RenameIndex(
            model_name='projectpilotjob',
            new_name='project_man_company_76b8b4_idx',
            old_name='ppilot_job_company_status_idx',
        ),
    ]
