# Generated by Django 4.2.10 on 2026-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager_agent', '0015_rename_ppilot_job_cu_created_idx_project_man_company_4041b1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmauditlog',
            name='action',
            field=models.CharField(choices=[('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('task_assigned', 'Task Assigned'), ('meeting_scheduled', 'Meeting Scheduled'), ('meeting_accepted', 'Meeting Accepted'), ('meeting_rejected', 'Meeting Rejected'), ('meeting_withdrawn', 'Meeting Withdrawn'), ('meeting_rescheduled', 'Meeting Rescheduled'), ('subtasks_generated', 'Subtasks Generated'), ('subtask_created', 'Subtask Created'), ('subtask_updated', 'Subtask Updated'), ('subtask_deleted', 'Subtask Deleted'), ('subtasks_reordered', 'Subtasks Reordered'), ('priority_updated', 'Priority Updated')], max_length=50),
        ),
    ]
