# Generated by Django 5.0.1 on 2025-12-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userprofile_role'),
        ('core', '0004_subtask'),
    ]

    operations = [
    ]
