# Generated by Django 5.0.1 on 2025-12-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_0004_alter_userprofile_role_0004_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_member', 'Team Member'), ('developer', 'Developer'), ('viewer', 'Viewer'), ('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent')], default='team_member', max_length=20),
        ),
    ]
