# Generated by Django 5.0.1 on 2025-12-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_percentage',
            field=models.IntegerField(blank=True, default=None, help_text='Manual progress percentage (0-100)', null=True),
        ),
    ]
