# Generated by Django 5.2.9 on 2025-12-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_frontline_agent_role'),
        ('core', '0008_aipredictorsubmission_blogtag_company_complaint_and_more'),
    ]

    operations = [
    ]
