# Generated by Django 5.0.1 on 2025-12-27 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aipredictorsubmission_blogtag_company_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='core.company'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('recruiter', 'Recruiter')], default='admin', max_length=50),
        ),
    ]
