# Generated by Django 5.0.1 on 2025-12-27 03:47

from django.db import migrations


def update_first_company_users_to_owner(apps, schema_editor):
    """Update the first company user for each company to owner role"""
    CompanyUser = apps.get_model('core', 'CompanyUser')
    
    # Group by company and get the first user (by id) for each company
    from django.db.models import Min
    
    first_user_ids = CompanyUser.objects.values('company').annotate(
        first_id=Min('id')
    ).values_list('first_id', flat=True)
    
    # Update those users to owner role if they're not already owner
    CompanyUser.objects.filter(id__in=first_user_ids).exclude(role='owner').update(role='owner')


def reverse_update_first_company_users_to_owner(apps, schema_editor):
    """Reverse: Set owner role users back to admin"""
    CompanyUser = apps.get_model('core', 'CompanyUser')
    CompanyUser.objects.filter(role='owner').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_company_to_userprofile_and_update_companyuser_roles'),
    ]

    operations = [
        migrations.RunPython(
            update_first_company_users_to_owner,
            reverse_update_first_company_users_to_owner
        ),
    ]
