# Generated by Django 5.2.9 on 2025-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251229_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('project_manager', 'Project Manager'), ('team_member', 'Team Member'), ('developer', 'Developer'), ('viewer', 'Viewer'), ('recruitment_agent', 'Recruitment Agent'), ('frontline_agent', 'Frontline Agent'), ('marketing_agent', 'Marketing Agent')], default='team_member', max_length=20),
        ),
    ]
