# Generated by Django 5.0.1 on 2025-12-29 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0004_add_frontline_agent_role_0008_aipredictorsubmission'),
        ('core', '0010_update_first_company_users_to_owner'),
    ]

    operations = [
    ]
