# Generated by Django 5.0.1 on 2026-01-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260106_2238'),
        ('core', '0018_merge_20260107_1739'),
    ]

    operations = [
    ]
