# Generated by Django 5.0.1 on 2026-01-13 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260109_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('company_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Company User Token',
                'verbose_name_plural': 'Company User Tokens',
            },
        ),
    ]
