# Generated by Django 5.0.1 on 2026-01-15 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_created_by_company_user_to_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_user_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company_user_owner',
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_projects', to='core.company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
