# Generated by Django 5.0.1 on 2026-01-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20260120_1714'),
        ('core', '0027_merge_20260120_1821'),
        ('core', '0027_merge_20260120_2102'),
    ]

    operations = [
    ]
