# Generated by Django 4.2.7 on 2026-01-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260122_2132'),
        ('core', '0028_merge_20260122_2215'),
    ]

    operations = [
    ]
