# Generated by Django 5.0.1 on 2026-01-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260122_2132'),
        ('core', '0028_merge_20260122_2215'),
    ]

    operations = [
    ]
