# Generated by Django 5.0.1 on 2026-01-23 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20260123_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModulePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('trial', 'Trial')], default='active', max_length=20)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid at time of purchase', max_digits=10, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Subscription expiration date (null for lifetime)', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_purchases', to='core.company')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_made', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Company Module Purchase',
                'verbose_name_plural': 'Company Module Purchases',
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['company', 'module_name', 'status'], name='core_compan_company_7db17c_idx'), models.Index(fields=['status', 'expires_at'], name='core_compan_status_855101_idx')],
                'unique_together': {('company', 'module_name')},
            },
        ),
    ]
