# Generated by Django 5.0.1 on 2026-01-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260122_1305'),
        ('core', '0030_add_company_module_purchase'),
    ]

    operations = [
    ]
