# Generated by Django 4.2.7 on 2026-02-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_update_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='module_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent')], max_length=50),
        ),
    ]
