# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_frontline_agent_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='frontline_widget_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
