# Generated by Django 5.1.7 on 2026-03-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodulepurchase',
            name='cancelled_reason',
            field=models.CharField(blank=True, help_text="Reason for cancellation (e.g., 'admin_deactivated', 'user_cancelled')", max_length=50, null=True),
        ),
    ]
