# Generated by Django 4.2.7 on 2026-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated'), ('team_member_added', 'Team Member Added'), ('deadline_approaching', 'Deadline Approaching'), ('milestone_reached', 'Milestone Reached'), ('mention', 'Mention'), ('meeting_request', 'Meeting Request')], max_length=50, null=True),
        ),
    ]
