# Generated by Django 5.0.1 on 2026-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='module_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('company_user', 'Company User'), ('project_manager', 'Project Manager'), ('recruitment_agent', 'Recruitment Agent'), ('frontline_agent', 'Frontline Agent'), ('marketing_agent', 'Marketing Agent'), ('operations_agent', 'Operations Agent')], default='admin', max_length=50),
        ),
    ]
