# Generated by Django 5.0.1 on 2026-04-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_cancelled_reason_to_modulepurchase'),
        ('core', '0037_add_operations_agent_choices'),
    ]

    operations = [
    ]
