# Generated by Django 4.2.7 on 2026-04-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_cancelled_reason_to_modulepurchase'),
        ('core', '0037_add_meeting_request_notification_type'),
        ('core', '0037_add_operations_agent_choices'),
    ]

    operations = [
    ]
