# Generated by Django 5.0.1 on 2026-04-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20260402_0105'),
        ('core', '0038_merge_20260402_2338'),
    ]

    operations = [
    ]
