# Generated by Django 4.2.7 on 2026-04-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_merge_20260402_0105'),
        ('core', '0038_merge_20260402_2338'),
    ]

    operations = [
    ]
