# Generated by Django 5.1.7 on 2026-04-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260415_1021'),
        ('core', '0040_company_frontline_allowed_origins'),
    ]

    operations = [
    ]
