# Generated by Django 5.1.7 on 2026-04-20 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20260420_1607'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent')], max_length=50, unique=True)),
                ('monthly_flat_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_charge_usd', models.DecimalField(decimal_places=2, default=0, help_text='Platform service fee added on top of provider cost (managed mode).', max_digits=10)),
                ('free_tokens_on_signup', models.BigIntegerField(default=1000000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Pricing Config',
                'verbose_name_plural': 'Admin Pricing Configs',
            },
        ),
        migrations.CreateModel(
            name='AgentTokenQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent')], max_length=50)),
                ('included_tokens', models.BigIntegerField(default=1000000)),
                ('used_tokens', models.BigIntegerField(default=0)),
                ('byok_tokens_info', models.BigIntegerField(default=0, help_text='Info-only counter of tokens spent via BYOK (not billable).')),
                ('last_reset_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_quotas', to='core.company')),
            ],
            options={
                'verbose_name': 'Agent Token Quota',
                'verbose_name_plural': 'Agent Token Quotas',
                'indexes': [models.Index(fields=['company', 'agent_name'], name='core_agentt_company_121643_idx')],
                'unique_together': {('company', 'agent_name')},
            },
        ),
        migrations.CreateModel(
            name='CompanyAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent')], max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok')], default='openai', max_length=20)),
                ('mode', models.CharField(choices=[('byok', 'Bring Your Own Key'), ('managed', 'Managed by Admin')], max_length=10)),
                ('encrypted_key', models.TextField(help_text='Fernet-encrypted provider key')),
                ('key_prefix', models.CharField(blank=True, help_text='First 4 chars, shown in UI', max_length=8)),
                ('key_suffix', models.CharField(blank=True, help_text='Last 4 chars, shown in UI', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Superadmin who assigned this managed key (null for BYOK)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_api_keys', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.company')),
            ],
            options={
                'verbose_name': 'Company API Key',
                'verbose_name_plural': 'Company API Keys',
                'indexes': [models.Index(fields=['company', 'agent_name', 'status'], name='core_compan_company_071aea_idx')],
                'unique_together': {('company', 'agent_name', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent')], max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok')], default='openai', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_requests', to='core.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_requests', to='core.companyuser')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_key_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='core_keyreq_company_7767d2_idx'), models.Index(fields=['status', '-created_at'], name='core_keyreq_status_f1efd2_idx')],
            },
        ),
    ]
