# Generated by Django 5.1.7 on 2026-04-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_api_key_and_token_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpricingconfig',
            name='free_tokens_on_signup',
        ),
        migrations.AddField(
            model_name='adminpricingconfig',
            name='free_tokens_on_purchase',
            field=models.BigIntegerField(default=1000000, help_text='Free tokens granted when a company purchases this agent (NOT on signup). Superadmin can change this per agent.'),
        ),
    ]
