# Generated by Django 5.1.7 on 2026-04-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_free_tokens_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('grok', 'xAI Grok')], max_length=20, unique=True)),
                ('encrypted_key', models.TextField(help_text='Fernet-encrypted provider key')),
                ('key_prefix', models.CharField(blank=True, max_length=8)),
                ('key_suffix', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_key_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform API Key',
                'verbose_name_plural': 'Platform API Keys',
            },
        ),
    ]
