# Generated by Django 5.1.7 on 2026-04-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_platform_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapikey',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('groq', 'Groq (Llama)'), ('grok', 'xAI Grok')], default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('groq', 'Groq (Llama)'), ('grok', 'xAI Grok')], default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformapikey',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude / Anthropic'), ('gemini', 'Google Gemini'), ('groq', 'Groq (Llama)'), ('grok', 'xAI Grok')], max_length=20, unique=True),
        ),
    ]
