# Generated by Django 4.2.10 on 2026-04-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_groq_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agenttokenquota',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='module_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('company_user', 'Company User'), ('project_manager', 'Project Manager'), ('recruitment_agent', 'Recruitment Agent'), ('frontline_agent', 'Frontline Agent'), ('marketing_agent', 'Marketing Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], default='admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent')], max_length=50),
        ),
    ]
