# Generated by Django 4.2.7 on 2026-04-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_company_hubspot_config'),
        ('core', '0047_sync_agenttokenquota_column_state'),
    ]

    operations = [
    ]
