# Generated by Django 4.2.10 on 2026-04-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_company_hubspot_config'),
        ('core', '0047_sync_agenttokenquota_column_state'),
    ]

    operations = [
    ]
