# Generated by Django 5.2.13 on 2026-04-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_managed_token_fields_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('company_user', 'Company User'), ('project_manager', 'Project Manager'), ('recruitment_agent', 'Recruitment Agent'), ('frontline_agent', 'Frontline Agent'), ('marketing_agent', 'Marketing Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], default='admin', max_length=50),
        ),
    ]
