# Generated by Django 5.0.1 on 2026-04-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20260424_1601'),
        ('core', '0049_add_managed_token_fields_to_model'),
    ]

    operations = [
    ]
