# Generated by Django 5.2.13 on 2026-04-29 01:55

from django.db import migrations, models


def _seed_hr_agent_pricing(apps, schema_editor):
    """Seed an AdminPricingConfig row for hr_agent so quota provisioning works
    when a tenant first purchases the module. Idempotent — uses get_or_create.
    """
    AdminPricingConfig = apps.get_model('core', 'AdminPricingConfig')
    AdminPricingConfig.objects.get_or_create(
        agent_name='hr_agent',
        defaults={'free_tokens_on_purchase': 1_000_000},
    )


def _unseed_hr_agent_pricing(apps, schema_editor):
    AdminPricingConfig = apps.get_model('core', 'AdminPricingConfig')
    AdminPricingConfig.objects.filter(agent_name='hr_agent').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_companyuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agenttokenquota',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='module_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent')], max_length=50),
        ),
        migrations.RunPython(_seed_hr_agent_pricing, _unseed_hr_agent_pricing),
    ]
