# Generated by Django 4.2.10 on 2026-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_add_agent_provider_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproviderusage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
