# Generated by Django 5.0.1 on 2026-05-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20260429_0005'),
        ('core', '0051_add_hr_agent_to_module_choices'),
    ]

    operations = [
    ]
