# Generated by Django 5.2.13 on 2026-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20260424_1601'),
        ('core', '0051_add_hr_agent_to_module_choices'),
    ]

    operations = [
    ]
