# Generated by Django 5.0.1 on 2026-05-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20260501_1508'),
        ('core', '0052_merge_20260501_2356'),
    ]

    operations = [
    ]
