# Generated by Django 5.2.13 on 2026-05-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20260501_2356'),
        ('core', '0053_merge_20260506_2252'),
    ]

    operations = [
    ]
