# Generated by Django 4.2.10 on 2026-05-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_agentproviderusage_id'),
        ('core', '0052_merge_20260501_2356'),
        ('core', '0052_quota_notification_flags'),
        ('core', '0053_merge_20260506_2252'),
    ]

    operations = [
    ]
