# Generated by Django 4.2.10 on 2026-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_merge_20260513_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='free_tokens_on_purchase',
            field=models.BigIntegerField(default=10000, help_text='Free tokens granted when a company purchases this agent (NOT on signup). Superadmin can change this per agent.'),
        ),
    ]
