# Generated by Django 4.2.10 on 2026-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_adminpricingconfig_free_tokens_on_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('comment_added', 'Comment Added'), ('project_updated', 'Project Updated'), ('team_member_added', 'Team Member Added'), ('deadline_approaching', 'Deadline Approaching'), ('milestone_reached', 'Milestone Reached'), ('mention', 'Mention'), ('meeting_request', 'Meeting Request'), ('quota_warning', 'Token Quota Warning'), ('quota_exhausted', 'Token Quota Exhausted')], max_length=50, null=True),
        ),
    ]
