# Generated by Django 4.2.10 on 2026-05-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_quota_notified_90pct'),
        ('core', '0056_alter_notification_notification_type'),
    ]

    operations = [
    ]
