# Generated by Django 5.0.1 on 2026-05-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20260507_0920'),
        ('core', '0054_merge_20260513_0857'),
        ('core', '0059_keyrequest_missing_fields'),
    ]

    operations = [
    ]
