# Generated by Django 4.2.10 on 2026-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_keyrequest_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpricingconfig',
            name='managed_key_tokens',
            field=models.BigIntegerField(default=0, help_text='Tokens granted when admin assigns a paid managed key via the request flow.'),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('payment_received', 'Payment Received'), ('key_assigned', 'Key Assigned'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
    ]
