# Generated by Django 4.2.10 on 2026-05-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_add_managed_key_tokens_to_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttokenquota',
            name='preferred_pool',
            field=models.CharField(choices=[('free', 'Free Platform Tokens'), ('managed', 'Managed Key Tokens')], default='managed', max_length=10),
        ),
    ]
