# Generated by Django 4.2.10 on 2026-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_add_managed_notification_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttokenquota',
            name='byok_token_limit',
            field=models.BigIntegerField(default=0),
        ),
    ]
