# Generated by Django 4.2.10 on 2026-05-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_add_byok_token_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttokenquota',
            name='byok_notified_100pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenttokenquota',
            name='byok_notified_80pct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenttokenquota',
            name='byok_notified_90pct',
            field=models.BooleanField(default=False),
        ),
    ]
