# Generated by Django 4.2.10 on 2026-05-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20260507_0920'),
        ('core', '0054_merge_20260513_0857'),
        ('core', '0064_byok_notification_flags'),
    ]

    operations = [
    ]
