# Generated by Django 4.2.10 on 2026-05-20 19:45
# Rewritten to use RunSQL to work around a django-mssql bug with ordered models.
#
# 2026-09-10: made engine-aware. The original body was raw T-SQL (DECLARE /
# sys.foreign_keys / EXEC), which MariaDB rejects with a 1064 syntax error. The
# schema change itself is trivial — make `core_keyrequest.requested_by_id`
# nullable — so each backend now gets its own spelling of it.
#
# This migration is DB-only; the matching model-state change lives in 0067.

from django.db import migrations


_MSSQL_FORWARD = """
DECLARE @fk NVARCHAR(256);
SELECT @fk = fk.name
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
WHERE fk.parent_object_id = OBJECT_ID('core_keyrequest')
  AND c.name = 'requested_by_id';
IF @fk IS NOT NULL
    EXEC('ALTER TABLE core_keyrequest DROP CONSTRAINT [' + @fk + ']');

ALTER TABLE core_keyrequest ALTER COLUMN requested_by_id bigint NULL;

ALTER TABLE core_keyrequest
ADD CONSTRAINT fk_keyreq_requested_by
FOREIGN KEY (requested_by_id) REFERENCES core_companyuser(id);
"""

_MSSQL_REVERSE = """
DECLARE @fk NVARCHAR(256);
SELECT @fk = fk.name
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
WHERE fk.parent_object_id = OBJECT_ID('core_keyrequest')
  AND c.name = 'requested_by_id';
IF @fk IS NOT NULL
    EXEC('ALTER TABLE core_keyrequest DROP CONSTRAINT [' + @fk + ']');

UPDATE core_keyrequest SET requested_by_id = (SELECT TOP 1 id FROM core_companyuser) WHERE requested_by_id IS NULL;
ALTER TABLE core_keyrequest ALTER COLUMN requested_by_id bigint NOT NULL;

ALTER TABLE core_keyrequest
ADD CONSTRAINT fk_keyreq_requested_by
FOREIGN KEY (requested_by_id) REFERENCES core_companyuser(id);
"""

# MySQL/MariaDB keeps the foreign key happily while the column's nullability
# changes, so there's no constraint drop/re-add dance to do here.
_MYSQL_FORWARD = "ALTER TABLE core_keyrequest MODIFY requested_by_id bigint NULL;"
_MYSQL_REVERSE = (
    "UPDATE core_keyrequest SET requested_by_id = "
    "(SELECT id FROM core_companyuser ORDER BY id LIMIT 1) WHERE requested_by_id IS NULL;"
)


def _forward(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'microsoft':
            cursor.execute(_MSSQL_FORWARD)
        elif vendor == 'mysql':
            cursor.execute(_MYSQL_FORWARD)
        # Any other backend: the model state in 0067 is authoritative and
        # Django will have built the column correctly from the start.


def _reverse(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'microsoft':
            cursor.execute(_MSSQL_REVERSE)
        elif vendor == 'mysql':
            cursor.execute(_MYSQL_REVERSE)
            cursor.execute(
                "ALTER TABLE core_keyrequest MODIFY requested_by_id bigint NOT NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20260521_0030'),
    ]

    operations = [
        migrations.RunPython(_forward, _reverse),
    ]
