# Generated by Django 4.2.10 on 2026-05-20 19:45
# Rewritten to use RunSQL to work around a django-mssql bug with ordered models.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20260521_0030'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DECLARE @fk NVARCHAR(256);
SELECT @fk = fk.name
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
WHERE fk.parent_object_id = OBJECT_ID('core_keyrequest')
  AND c.name = 'requested_by_id';
IF @fk IS NOT NULL
    EXEC('ALTER TABLE core_keyrequest DROP CONSTRAINT [' + @fk + ']');

ALTER TABLE core_keyrequest ALTER COLUMN requested_by_id bigint NULL;

ALTER TABLE core_keyrequest
ADD CONSTRAINT fk_keyreq_requested_by
FOREIGN KEY (requested_by_id) REFERENCES core_companyuser(id);
""",
            reverse_sql="""
DECLARE @fk NVARCHAR(256);
SELECT @fk = fk.name
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
WHERE fk.parent_object_id = OBJECT_ID('core_keyrequest')
  AND c.name = 'requested_by_id';
IF @fk IS NOT NULL
    EXEC('ALTER TABLE core_keyrequest DROP CONSTRAINT [' + @fk + ']');

UPDATE core_keyrequest SET requested_by_id = (SELECT TOP 1 id FROM core_companyuser) WHERE requested_by_id IS NULL;
ALTER TABLE core_keyrequest ALTER COLUMN requested_by_id bigint NOT NULL;

ALTER TABLE core_keyrequest
ADD CONSTRAINT fk_keyreq_requested_by
FOREIGN KEY (requested_by_id) REFERENCES core_companyuser(id);
""",
        ),
    ]
