# Generated by Django 4.2.10 on 2026-05-20 19:59
# Rewritten to state-only: DB column was already made nullable by 0066 (RunSQL).
# AlterField crashes on mssql when the model has Meta.ordering = ['-created_at'].

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_keyrequest_requested_by_nullable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # DB already updated by 0066
            state_operations=[
                migrations.AlterField(
                    model_name='keyrequest',
                    name='requested_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_requests', to='core.companyuser'),
                ),
            ],
        ),
    ]
