# Generated by Django 5.2.13 on 2026-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20260521_0934'),
        ('core', '0067_alter_keyrequest_requested_by'),
    ]

    operations = [
    ]
