# Generated by Django 5.0.1 on 2026-05-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20260516_0125'),
        ('core', '0060_merge_20260521_0934'),
        ('core', '0067_alter_keyrequest_requested_by'),
    ]

    operations = [
    ]
