# Generated by Django 5.2.13 on 2026-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_merge_20260522_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='frontline_slack_webhook_url',
            field=models.URLField(blank=True, default='', help_text='Slack incoming-webhook URL for Frontline notifications.', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='frontline_teams_webhook_url',
            field=models.URLField(blank=True, default='', help_text='MS Teams incoming-webhook URL for Frontline notifications.', max_length=500),
        ),
    ]
