# Generated by Django 5.2.13 on 2026-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_frontline_channel_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_slack_webhook_url',
            field=models.URLField(blank=True, default='', help_text='Slack incoming-webhook URL for HR notifications.', max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_teams_webhook_url',
            field=models.URLField(blank=True, default='', help_text='MS Teams incoming-webhook URL for HR notifications.', max_length=500),
        ),
    ]
