# Generated by Django 5.0.1 on 2026-05-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_merge_20260525_0145'),
        ('core', '0070_hr_channel_webhooks'),
    ]

    operations = [
    ]
