# Generated by Django 4.2.10 on 2026-05-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20260516_0125'),
        ('core', '0070_hr_channel_webhooks'),
    ]

    operations = [
    ]
