# Generated by Django 4.2.10 on 2026-05-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20260526_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttokenquota',
            name='preferred_pool',
            field=models.CharField(blank=True, choices=[('free', 'Free Platform Tokens'), ('managed', 'Managed Key Tokens'), ('byok', 'BYOK Key'), ('none', 'Disabled (no key)')], default='managed', max_length=10, null=True),
        ),
    ]
