# Generated by Django 4.2.10 on 2026-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_add_preferred_pool_none_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('ai_sdr_agent', 'AI SDR Agent')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agenttokenquota',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('ai_sdr_agent', 'AI SDR Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('ai_sdr_agent', 'AI SDR Agent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='agent_name',
            field=models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('ai_sdr_agent', 'AI SDR Agent')], max_length=50),
        ),
    ]
