# Generated by Django 5.2.13 on 2026-06-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20260530_0056'),
        ('core', '0072_add_preferred_pool_none_choice'),
    ]

    operations = [
    ]
