# Generated by Django 5.2.13 on 2026-06-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_20260603_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Every N days/weeks/months.')),
                ('weekdays', models.CharField(blank=True, default='', help_text='Weekly only. Comma-separated weekday indices, Monday=0..Sunday=6. Empty = every day of the chosen interval.', max_length=32)),
                ('starts_on', models.DateField(help_text='Date of the first occurrence.')),
                ('ends_on', models.DateField(blank=True, help_text='Optional cutoff. No occurrences are generated past this date.', null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Optional cap on number of generated tasks.', null=True)),
                ('count_generated', models.PositiveIntegerField(default=0)),
                ('last_generated_on', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField(help_text='Date of the next planned occurrence.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_task', models.OneToOneField(help_text='The task that future occurrences are cloned from.', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence', to='core.task')),
            ],
        ),
    ]
