# Generated by Django 4.2.10 on 2026-06-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_merge_20260530_0056'),
        ('core', '0074_ai_sdr_pricing_and_preferred_pool_free'),
    ]

    operations = [
    ]
