# Generated by Django 4.2.10 on 2026-06-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_merge_20260602_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpricingconfig',
            name='yearly_discount_months',
            field=models.DecimalField(decimal_places=1, default=12, help_text='How many months to charge for a yearly plan (e.g. 10 = 2 months free). Default 12 = no discount.', max_digits=4),
        ),
        migrations.AddField(
            model_name='agenttokenquota',
            name='next_reset_at',
            field=models.DateTimeField(blank=True, help_text='Next weekly token reset timestamp. Null = no recurring reset.', null=True),
        ),
        migrations.AddField(
            model_name='companyapikey',
            name='renewal_period',
            field=models.CharField(choices=[('none', 'One-time (no renewal)'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Billing renewal cycle. Token quota resets weekly regardless.', max_length=10),
        ),
        migrations.AddField(
            model_name='companyapikey',
            name='tokens_per_period',
            field=models.BigIntegerField(default=0, help_text='Tokens to grant at each weekly reset. 0 = use managed_included_tokens as a one-time set.'),
        ),
        migrations.AddField(
            model_name='companyapikey',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Key expiry date. After this date the key is auto-expired and company must renew.', null=True),
        ),
        migrations.AddField(
            model_name='keyrequest',
            name='preferred_duration',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', help_text='Duration company is requesting: monthly or yearly.', max_length=10),
        ),
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='managed_key_tokens',
            field=models.BigIntegerField(default=0, help_text='Default tokens per weekly reset cycle when admin assigns a managed key.'),
        ),
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='monthly_flat_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Key cost per month (shown as "/month" on pricing page).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='agenttokenquota',
            name='preferred_pool',
            field=models.CharField(blank=True, choices=[('free', 'Free Platform Tokens'), ('managed', 'Managed Key Tokens'), ('byok', 'BYOK Key'), ('none', 'Disabled (no key)')], default='managed', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agenttokenquota',
            index=models.Index(fields=['next_reset_at'], name='core_agentt_next_re_80b939_idx'),
        ),
    ]
