# Generated by Django 4.2.10 on 2026-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_renewal_and_duration_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminpricingconfig',
            name='yearly_discount_months',
        ),
        migrations.AddField(
            model_name='adminpricingconfig',
            name='yearly_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % on yearly plan (0 = no discount, 20 = 20% off, max 100).', max_digits=5),
        ),
    ]
