# Generated by Django 4.2.10 on 2026-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_rename_discount_months_to_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodulepurchase',
            name='history_kept',
            field=models.BooleanField(blank=True, help_text='When deactivated by admin: True = history preserved, False = history deleted, None = not applicable', null=True),
        ),
    ]
