# Generated by Django 4.2.10 on 2026-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_history_kept_to_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='is_renewal',
            field=models.BooleanField(default=False, help_text='True when this request is a renewal of an expired key.'),
        ),
    ]
