# Generated by Django 4.2.10 on 2026-06-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_is_renewal_to_keyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpricingconfig',
            name='monthly_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % on monthly plan (0 = no discount, 10 = 10% off, max 100).', max_digits=5),
        ),
    ]
