# Generated by Django 4.2.10 on 2026-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_add_monthly_discount_to_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='discount_pct_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
