# Generated by Django 4.2.10 on 2026-06-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_task_recurrence'),
        ('core', '0081_add_discount_pct_snapshot'),
    ]

    operations = [
    ]
