# Generated by Django 5.0.1 on 2026-06-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_task_recurrence'),
        ('core', '0081_add_discount_pct_snapshot'),
    ]

    operations = [
    ]
