# Generated by Django 5.0.1 on 2026-06-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_companyapikey_and_quota_orphans'),
        ('core', '0082_merge_20260604_2320'),
        ('core', '0082_merge_20260609_0307'),
    ]

    operations = [
    ]
