# Generated by Django 5.0.1 on 2026-06-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_merge_20260613_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttokenquota',
            name='next_reset_at',
            field=models.DateTimeField(blank=True, help_text='Next weekly token reset timestamp. Null = no recurring reset.', null=True),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='renewal_period',
            field=models.CharField(choices=[('none', 'One-time (no renewal)'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='none', help_text='Billing renewal cycle. Token quota resets weekly regardless.', max_length=10),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='tokens_per_period',
            field=models.BigIntegerField(default=0, help_text='Tokens to grant at each weekly reset. 0 = use managed_included_tokens as a one-time set.'),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Key expiry date. After this date the key is auto-expired and company must renew.', null=True),
        ),
    ]
