# Generated by Django 4.2.10 on 2026-07-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_indexes_validators_clean'),
        ('core', '0084_alter_adminpricingconfig_agent_name_and_more'),
        ('core', '0084_alter_agenttokenquota_next_reset_at_and_more'),
    ]

    operations = [
    ]
