# Generated by Django 4.2.10 on 2026-07-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20260707_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='reset_otp_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
