# Generated by Django 5.2.13 on 2026-07-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_merge_20260706_1855'),
        ('core', '0086_companyuser_reset_otp_companyuser_reset_otp_expires'),
    ]

    operations = [
    ]
