# Generated by Django 5.2.13 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_merge_20260708_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_frontline_tutorial',
            field=models.BooleanField(default=False, help_text='Whether the user has completed or skipped the Frontline Agent onboarding tutorial'),
        ),
    ]
