# Generated by Django 4.2.10 on 2026-07-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_userprofile_has_seen_frontline_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='google_calendar_config',
            field=models.JSONField(blank=True, default=dict, help_text='Per-company Google Calendar OAuth config: {connected, refresh_token, google_email, calendar_id, last_error}.'),
        ),
    ]
