# Generated by Django 4.2.10 on 2026-07-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_company_google_calendar_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Stable machine key, e.g. 'recruitment_agent'. Never change once in use.", unique=True)),
                ('name', models.CharField(help_text='Display name shown in the UI.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Short marketing blurb shown on the pricing / module cards.')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature bullet strings shown on the pricing card.')),
                ('default_provider', models.CharField(default='groq', help_text="LLM provider this agent uses by default (e.g. 'groq', 'openai').", max_length=20)),
                ('is_purchasable', models.BooleanField(default=True, help_text='Whether companies can buy this agent as a module.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to retire an agent — hides it from lists without breaking existing rows.')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in lists.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='adminpricingconfig',
            name='agent_name',
            field=models.CharField(choices=[], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='agenttokenquota',
            name='agent_name',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='agent_name',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='module_name',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='keyrequest',
            name='agent_name',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
