# Generated by Django 4.2.10 on 2026-08-04 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_adminpricingconfig_agent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('ai_sdr_agent', 'AI SDR Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('exec_meeting_agent', 'AI Executive Meeting Assistant')], max_length=50)),
                ('reset_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tokens_used_before_reset', models.BigIntegerField(default=0)),
                ('new_included_limit', models.BigIntegerField(default=0)),
                ('next_reset_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reset_logs', to='core.company')),
            ],
            options={
                'verbose_name': 'Weekly Reset Log',
                'verbose_name_plural': 'Weekly Reset Logs',
                'ordering': ['-reset_at'],
                'indexes': [models.Index(fields=['company', 'agent_name', '-reset_at'], name='core_weekly_company_8ba004_idx')],
            },
        ),
    ]
