# Generated by Django 4.2.10 on 2026-08-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_weeklyresetlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyapikey',
            name='reset_interval_days',
            field=models.PositiveIntegerField(default=7, help_text='Days between automatic token resets (default 7). Used when renewal is active.'),
        ),
        migrations.AlterField(
            model_name='companyapikey',
            name='tokens_per_period',
            field=models.BigIntegerField(default=0, help_text='Tokens to grant at each reset cycle. 0 = use managed_included_tokens as a one-time set.'),
        ),
    ]
