# Generated by Django 4.2.10 on 2026-08-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_companyapikey_reset_interval_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('ai_sdr_agent', 'AI SDR Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('exec_meeting_agent', 'AI Executive Meeting Assistant')], db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('duration_days', models.PositiveIntegerField(help_text='How long the purchase stays active, in days.')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are shown to companies.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Plan',
                'verbose_name_plural': 'Agent Plans',
                'ordering': ['agent_name', 'sort_order', 'duration_days'],
                'indexes': [models.Index(fields=['agent_name', 'is_active'], name='core_agentp_agent_n_12613b_idx')],
            },
        ),
    ]
