# Generated by Django 4.2.10 on 2026-08-28 17:46

from django.db import migrations, models


def clear_bogus_last_reset(apps, schema_editor):
    """Null out last_reset_at values that were never real resets.

    The field was auto_now_add, so every row carries its creation timestamp
    regardless of whether a reset ever happened - which the UI would now
    render as a genuine "Last reset". Clear it for quotas with no logged
    reset; quotas that DO have a reset log keep their value (and the log is
    the primary source for the UI anyway).
    """
    AgentTokenQuota = apps.get_model('core', 'AgentTokenQuota')
    WeeklyResetLog = apps.get_model('core', 'WeeklyResetLog')

    logged = set(
        WeeklyResetLog.objects.values_list('company_id', 'agent_name').distinct()
    )
    for quota in AgentTokenQuota.objects.exclude(last_reset_at__isnull=True).iterator():
        if (quota.company_id, quota.agent_name) not in logged:
            AgentTokenQuota.objects.filter(pk=quota.pk).update(last_reset_at=None)


def noop_reverse(apps, schema_editor):
    """Cleared timestamps were meaningless; nothing to restore."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_agentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttokenquota',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(clear_bogus_last_reset, noop_reverse),
    ]
