# Generated by Django 4.2.10 on 2026-08-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_agentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrequest',
            name='plan_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration (days) of the AgentPlan the company selected when requesting.', null=True),
        ),
    ]
