# Generated by Django 4.2.10 on 2026-08-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0096_alter_agenttokenquota_last_reset_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(choices=[('recruitment_agent', 'Recruitment Agent'), ('marketing_agent', 'Marketing Agent'), ('project_manager_agent', 'Project Manager Agent'), ('frontline_agent', 'Frontline Agent'), ('operations_agent', 'Operations Agent'), ('ai_sdr_agent', 'AI SDR Agent'), ('reply_draft_agent', 'Reply Draft Agent'), ('hr_agent', 'HR Support Agent'), ('exec_meeting_agent', 'AI Executive Meeting Assistant')], max_length=50)),
                ('event', models.CharField(choices=[('assigned', 'Key Assigned'), ('renewed', 'Key Renewed'), ('expired', 'Key Expired'), ('revoked', 'Key Revoked')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider', models.CharField(blank=True, max_length=20, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('tokens_per_period', models.BigIntegerField(default=0)),
                ('renewal_period', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_events_caused', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_events', to='core.company')),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.companyapikey')),
            ],
            options={
                'verbose_name': 'Key Event Log',
                'verbose_name_plural': 'Key Event Logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['company', 'agent_name', '-occurred_at'], name='core_keyeve_company_43ec1c_idx')],
            },
        ),
    ]
