# Generated by Django 4.2.10 on 2026-08-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_stripe_subscription_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text="Stripe's `evt_...` id. Unique — this is the dedup key.", max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterField(
            model_name='companymodulepurchase',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Locally-owned expiry: legacy one-time purchases and admin-granted complimentary access. Stripe subscriptions use current_period_end instead.', null=True),
        ),
    ]
