# Generated by Django 4.2.10 on 2026-08-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_stripe_webhook_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Legacy one-time-purchase length. Ignored for Stripe subscriptions.'),
        ),
    ]
