# Generated by Django 4.2.10 on 2026-09-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_keyeventlog'),
        ('core', '0098_alter_agentplan_duration_days'),
    ]

    operations = [
    ]
