# Generated by Django 4.2.10 on 2026-09-03 04:21
#
# Adds the "one active plan per agent+interval" constraint that AgentPlan's
# docstring has always claimed but nothing enforced. Existing databases already
# hold duplicates (one agent had seven Stripe Prices as a result), so they must be
# resolved BEFORE the constraint is applied or the migration cannot go on.

from django.db import migrations, models


def deactivate_duplicate_plans(apps, schema_editor):
    """Leave one active plan per (agent_name, billing_interval).

    Deactivates rather than deletes: a losing row may still own the Stripe Price a
    live subscription is billing against, and dropping it would strand that
    subscriber. Keeps the most recently updated row, which is the one an admin last
    touched and therefore the price they believe is current.
    """
    AgentPlan = apps.get_model('core', 'AgentPlan')

    seen = set()
    stale_ids = []
    # Newest first, so the first row seen for a key is the one to keep.
    for plan in AgentPlan.objects.filter(is_active=True).order_by('-updated_at', '-id'):
        key = (plan.agent_name, plan.billing_interval)
        if key in seen:
            stale_ids.append(plan.id)
        else:
            seen.add(key)

    if stale_ids:
        AgentPlan.objects.filter(id__in=stale_ids).update(is_active=False)


def noop_reverse(apps, schema_editor):
    """Nothing to undo — reactivating duplicates would re-break the invariant."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_agentplan_duration_days'),
    ]

    operations = [
        migrations.RunPython(deactivate_duplicate_plans, noop_reverse),
        migrations.AddConstraint(
            model_name='agentplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('agent_name', 'billing_interval'), name='uniq_active_plan_per_agent_interval'),
        ),
    ]
