# Generated by Django 4.2.10 on 2026-09-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_agentplan_unique_active_interval'),
        ('core', '0099_merge_20260907_2057'),
    ]

    operations = [
    ]
