# Generated by Django 4.2.10 on 2026-09-16 20:25
# Shared busy-time table for meeting clash checks across the PM, HR and
# Frontline agents. See core/scheduling and MDS/MEETING_CONFLICTS_ACROSS_AGENTS.md.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0101_project_task_indexes_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('pm', 'Project Manager'), ('hr', 'HR'), ('frontline', 'Frontline')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField(help_text="Primary key of the meeting in the source agent's table.")),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('participant', 'Participant')], default='participant', max_length=12)),
                ('response', models.CharField(blank=True, default='', help_text='pending / accepted / counter_proposed / scheduled. Shown in clash messages; every stored row counts as busy.', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_private', models.BooleanField(default=False, help_text='Hide the title from other agents (HR exit interviews etc.).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'ends_at'], name='calblock_user_end_idx'), models.Index(fields=['company', 'starts_at'], name='calblock_company_start_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='calendarblock',
            constraint=models.UniqueConstraint(fields=('source', 'source_id', 'user'), name='calblock_unique'),
        ),
        migrations.AddConstraint(
            model_name='calendarblock',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='calblock_ends_after_start'),
        ),
    ]
