# Generated by Django 5.2.13 on 2026-04-29 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0050_alter_companyuser_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(help_text='Primary contact — unique per company.', max_length=254)),
                ('personal_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('job_title', models.CharField(blank=True, default='', max_length=160)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('employment_status', models.CharField(choices=[('candidate', 'Candidate (offer signed, not started)'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('on_leave', 'On Leave'), ('probation', 'Probation'), ('notice', 'Serving Notice'), ('offboarded', 'Offboarded')], default='active', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contractor'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('probation_end_date', models.DateField(blank=True, help_text='Used by reminder agent to flag end-of-probation reviews.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Last working day if offboarded.', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('work_anniversary_month_day', models.CharField(blank=True, default='', help_text='MM-DD shortcut for the anniversary reminder agent.', max_length=5)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Tenant-specific attributes (location, cost center, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
                ('company_user', models.OneToOneField(blank=True, help_text='Linked dashboard login if this employee has a self-service account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employee', to='core.companyuser')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr_agent.employee')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='HRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('document_type', models.CharField(choices=[('handbook', 'Employee Handbook'), ('policy', 'Policy'), ('procedure', 'Procedure / SOP'), ('offer_letter', 'Offer Letter'), ('contract', 'Contract'), ('id_proof', 'ID / KYC Proof'), ('payslip', 'Payslip'), ('payroll', 'Payroll / Compensation'), ('performance_review', 'Performance Review'), ('leave_form', 'Leave Form'), ('training', 'Training Material'), ('benefits', 'Benefits Doc'), ('compliance', 'Compliance Doc'), ('other', 'Other')], default='policy', max_length=24)),
                ('confidentiality', models.CharField(choices=[('public', 'Public'), ('employee', 'All Employees'), ('manager', 'Managers + HR'), ('hr_only', 'HR Only')], db_index=True, default='employee', max_length=12)),
                ('file_path', models.CharField(help_text='Path under MEDIA_ROOT.', max_length=1000)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('md', 'Markdown'), ('html', 'HTML'), ('other', 'Other')], default='other', max_length=10)),
                ('file_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('document_content', models.TextField(blank=True, default='', help_text='Extracted plain text.')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('chunks_processed', models.IntegerField(default=0)),
                ('chunks_total', models.IntegerField(default=0)),
                ('is_indexed', models.BooleanField(default=False)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=100)),
                ('extracted_fields', models.JSONField(blank=True, default=dict, help_text='Auto-extracted key fields, e.g. {"salary": ..., "start_date": ...}.')),
                ('retention_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_documents', to='core.company')),
                ('employee', models.ForeignKey(blank=True, help_text='Set when this is a per-employee document. Restricts visibility to the employee + HR.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='hr_agent.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRDocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.TextField(blank=True, help_text='Vector embedding as JSON; nvarchar(max) on MSSQL.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='hr_agent.hrdocument')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='HRKnowledgeChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HR chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_knowledge_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRKnowledgeChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, help_text='Full QA response payload (citations, confidence) for assistant rows.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hr_agent.hrknowledgechat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('meeting_type', models.CharField(choices=[('onboarding_orientation', 'Onboarding Orientation'), ('one_on_one', '1:1 with Manager'), ('performance_review', 'Performance Review'), ('mid_year_check_in', 'Mid-year Check-in'), ('exit_interview', 'Exit Interview'), ('grievance_hearing', 'Grievance Hearing'), ('training_session', 'Training Session'), ('benefits_consult', 'Benefits Consultation'), ('other', 'Other')], default='one_on_one', max_length=30)),
                ('visibility', models.CharField(choices=[('company', 'Company-visible'), ('private', 'Private (participants + HR only)')], default='company', max_length=10)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('reminder_24h_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_15m_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_meetings', to='core.company')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_meetings_organized', to='hr_agent.employee')),
                ('participants', models.ManyToManyField(blank=True, related_name='hr_meetings_attending', to='hr_agent.employee')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='HRNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('birthday', 'Birthday'), ('work_anniversary', 'Work Anniversary'), ('probation_ending', 'Probation Ending'), ('review_due', 'Review Due'), ('document_expiring', 'Document Expiring'), ('approval_pending', 'Approval Pending'), ('leave_request_status', 'Leave Request Status'), ('onboarding_step', 'Onboarding Step'), ('compliance_training', 'Compliance Training'), ('system', 'System')], default='system', max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], default='email', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(help_text='Use {{employee_name}}, {{event_date}}, {{document_title}} placeholders.')),
                ('trigger_config', models.JSONField(blank=True, default=dict, help_text='e.g. {"on": "probation_ending", "days_before": 7}')),
                ('use_llm_personalization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_notification_templates', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_conditions', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(default=list, help_text='List of step dicts. HR-specific step types include `provision_account`, `assign_training`, `update_leave_balance`, `schedule_meeting`, plus the generic `send_email`, `branch`, `wait`.')),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_workflows', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRWorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused (waiting)'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('awaiting_approval', 'Awaiting Approval'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('pause_state', models.JSONField(blank=True, default=dict)),
                ('resume_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, help_text='The employee this execution is operating on, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_workflow_executions', to='hr_agent.employee')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_workflow_executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='hr_agent.hrworkflow')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation / PTO'), ('sick', 'Sick'), ('parental', 'Parental'), ('bereavement', 'Bereavement'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=20)),
                ('accrued_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr_agent.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation / PTO'), ('sick', 'Sick'), ('parental', 'Parental'), ('bereavement', 'Bereavement'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals_made', to='hr_agent.employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr_agent.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, default='', help_text='Falls back to recipient_employee.work_email if blank.', max_length=254)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('dead_lettered', 'Dead-lettered')], default='pending', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deferred_reason', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_scheduled_notifications', to='core.company')),
                ('recipient_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_scheduled_notifications', to='hr_agent.employee')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='hr_agent.hrdocument')),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='hr_agent.hrmeeting')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='hr_agent.hrnotificationtemplate')),
                ('related_leave_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='hr_agent.leaverequest')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employment_status'], name='hr_agent_em_company_930b62_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'department'], name='hr_agent_em_company_c09517_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'manager'], name='hr_agent_em_company_c7a955_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['probation_end_date'], name='hr_agent_em_probati_f69fb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'work_email')},
        ),
        migrations.AddIndex(
            model_name='hrdocument',
            index=models.Index(fields=['company', 'document_type'], name='hr_agent_hr_company_f49171_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocument',
            index=models.Index(fields=['company', 'confidentiality'], name='hr_agent_hr_company_72928e_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocument',
            index=models.Index(fields=['employee', 'document_type'], name='hr_agent_hr_employe_54ebec_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocument',
            index=models.Index(fields=['processing_status'], name='hr_agent_hr_process_d8d29e_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdocumentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='hr_agent_hr_documen_429881_idx'),
        ),
        migrations.AddIndex(
            model_name='hrmeeting',
            index=models.Index(fields=['company', 'scheduled_at'], name='hr_agent_hr_company_20d34e_idx'),
        ),
        migrations.AddIndex(
            model_name='hrmeeting',
            index=models.Index(fields=['meeting_type', 'status'], name='hr_agent_hr_meeting_5b74e2_idx'),
        ),
        migrations.AddIndex(
            model_name='hrmeeting',
            index=models.Index(fields=['scheduled_at', 'reminder_24h_sent_at'], name='hr_agent_hr_schedul_cc3b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='hrmeeting',
            index=models.Index(fields=['scheduled_at', 'reminder_15m_sent_at'], name='hr_agent_hr_schedul_ed84e9_idx'),
        ),
        migrations.AddIndex(
            model_name='hrworkflowexecution',
            index=models.Index(fields=['status', 'started_at'], name='hr_agent_hr_status_75bd2a_idx'),
        ),
        migrations.AddIndex(
            model_name='hrworkflowexecution',
            index=models.Index(fields=['employee', 'status'], name='hr_agent_hr_employe_63f67c_idx'),
        ),
        migrations.AddIndex(
            model_name='leavebalance',
            index=models.Index(fields=['employee', 'leave_type'], name='hr_agent_le_employe_a585d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='hr_agent_le_employe_363b52_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='hr_agent_le_status_3393a2_idx'),
        ),
        migrations.AddIndex(
            model_name='hrschedulednotification',
            index=models.Index(fields=['status', 'scheduled_at'], name='hr_agent_hr_status_6b78bf_idx'),
        ),
        migrations.AddIndex(
            model_name='hrschedulednotification',
            index=models.Index(fields=['status', 'next_retry_at'], name='hr_agent_hr_status_d9de80_idx'),
        ),
        migrations.AddIndex(
            model_name='hrschedulednotification',
            index=models.Index(fields=['company'], name='hr_agent_hr_company_f2741e_idx'),
        ),
    ]
