# Generated by Django 5.2.13 on 2026-05-01 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20260424_1601'),
        ('hr_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django auth.User row this employee corresponds to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company_user',
            field=models.OneToOneField(blank=True, help_text='Optional dashboard-login link for self-service.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employee', to='core.companyuser'),
        ),
    ]
