# Generated by Django 5.2.13 on 2026-05-02 00:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20260501_1508'),
        ('hr_agent', '0002_employee_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMeetingSchedulerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Meeting chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_meeting_scheduler_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HRMeetingSchedulerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, help_text='Structured payload from the LLM (e.g. created meeting id, agenda).', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hr_agent.hrmeetingschedulerchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
