# Generated by Django 5.2.13 on 2026-05-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_20260429_0005'),
        ('hr_agent', '0003_meeting_scheduler_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, help_text='Original document this is a revision of.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='hr_agent.hrdocument'),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Points to the newer revision; non-null = excluded from retrieval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_revisions', to='hr_agent.hrdocument'),
        ),
        migrations.AddField(
            model_name='hrdocument',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('region', models.CharField(blank=True, default='', help_text='Optional region/locale code (e.g. "US-CA"). Blank = company-wide.', max_length=64)),
                ('is_working_day', models.BooleanField(default=False, help_text='False = day off (default). True lets you mark working bridges around official holidays.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_holidays', to='core.company')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['company', 'date'], name='hr_agent_ho_company_b1557d_idx')],
                'unique_together': {('company', 'date', 'region')},
            },
        ),
        migrations.CreateModel(
            name='LeaveAccrualPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation / PTO'), ('sick', 'Sick'), ('parental', 'Parental'), ('bereavement', 'Bereavement'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=20)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('annual', 'Annual')], default='monthly', max_length=12)),
                ('days_per_period', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Cap for accrued+carryover; null = uncapped.', max_digits=6, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Most recent successful accrual tick. Used to skip duplicate periods.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_accrual_policies', to='core.company')),
            ],
            options={
                'ordering': ['leave_type'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='hr_agent_le_company_e6e772_idx')],
                'unique_together': {('company', 'leave_type')},
            },
        ),
    ]
