# Generated by Django 5.2.13 on 2026-05-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_agent', '0004_doc_versioning_holiday_accrual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date this compensation level took effect.')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 code, e.g. USD, EUR, PKR.', max_length=3)),
                ('pay_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('biweekly', 'Biweekly'), ('weekly', 'Weekly'), ('annual', 'Annual'), ('hourly', 'Hourly')], default='annual', max_length=10)),
                ('bonus_target_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Target annual bonus as percent of base.', max_digits=5, null=True)),
                ('equity_grant_value', models.DecimalField(blank=True, decimal_places=2, help_text='Notional value of equity granted at this change, if any.', max_digits=12, null=True)),
                ('grade', models.CharField(blank=True, default='', help_text='Internal level / band, e.g. "L4", "Senior".', max_length=40)),
                ('reason', models.CharField(choices=[('initial', 'Initial offer'), ('annual_raise', 'Annual raise'), ('promotion', 'Promotion'), ('market_adjustment', 'Market adjustment'), ('contract_renewal', 'Contract renewal'), ('correction', 'Correction'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='hr_agent.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_compensation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['employee', '-effective_date'], name='hr_agent_co_employe_ea3fb8_idx')],
            },
        ),
    ]
