# Generated by Django 5.2.13 on 2026-05-07 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20260506_2252'),
        ('hr_agent', '0005_compensation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Legacy free-text — prefer department_obj going forward.', max_length=120),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', help_text='Short identifier (ENG, SALES, OPS).', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to='hr_agent.employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr_agent.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='department_obj',
            field=models.ForeignKey(blank=True, help_text='Canonical department FK. Backfilled from `department` string.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr_agent.department'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'is_active'], name='hr_agent_de_company_ead057_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
    ]
