# Generated by Django 5.2.13 on 2026-05-07 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20260506_2252'),
        ('hr_agent', '0007_backfill_department_obj'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "H1 2026", "Annual 2025".', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('self_review_due', models.DateField(blank=True, null=True)),
                ('manager_review_due', models.DateField(blank=True, null=True)),
                ('calibration_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft (cycle defined, reviews not generated)'), ('active', 'Active (reviews in progress)'), ('closed', 'Closed (read-only)'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_cycles', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_review_cycles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('self_in_progress', 'Self-review in progress'), ('manager_in_progress', 'Manager review in progress'), ('awaiting_calibration', 'Awaiting calibration'), ('closed', 'Closed (released)'), ('skipped', 'Skipped (not applicable)')], default='not_started', max_length=24)),
                ('self_summary', models.TextField(blank=True, default='')),
                ('manager_summary', models.TextField(blank=True, default='')),
                ('strengths', models.TextField(blank=True, default='')),
                ('growth_areas', models.TextField(blank=True, default='')),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of {goal, target_date, weight_pct} dicts.')),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — Below expectations'), (2, '2 — Approaching expectations'), (3, '3 — Meets expectations'), (4, '4 — Exceeds expectations'), (5, '5 — Far exceeds expectations')], null=True)),
                ('self_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('visible_to_employee', models.BooleanField(default=False, help_text='Set when the review is released to the reviewee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr_agent.employee')),
                ('reviewer', models.ForeignKey(blank=True, help_text='Manager or peer who fills the manager-review portion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to='hr_agent.employee')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hr_agent.performancereviewcycle')),
            ],
            options={
                'ordering': ['-cycle__period_start', 'employee__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='performancereviewcycle',
            index=models.Index(fields=['company', 'status'], name='hr_agent_pe_company_abcd29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereviewcycle',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['employee', 'status'], name='hr_agent_pe_employe_6c4257_idx'),
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['cycle', 'status'], name='hr_agent_pe_cycle_i_e20c19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together={('cycle', 'employee')},
        ),
    ]
