# Generated by Django 5.2.13 on 2026-05-13 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20260501_2356'),
        ('hr_agent', '0008_perf_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdocumentchunk',
            name='section_heading',
            field=models.CharField(blank=True, default='', help_text='The detected heading (Markdown #, ALL-CAPS, Article/Section marker) that opened the section this chunk belongs to. Empty for non-section-aware types.', max_length=300),
        ),
        migrations.CreateModel(
            name='HRAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Dot-path verb: employee.update, compensation.create, compensation.delete, review.update …', max_length=80)),
                ('target_type', models.CharField(help_text='Lower-case model name: employee, compensation, review …', max_length=40)),
                ('target_id', models.IntegerField(help_text='Primary key of the changed row.')),
                ('diff', models.JSONField(blank=True, default=dict, help_text='{"before": {...}, "after": {...}} or {"created": {...}} or {"deleted": {...}}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The CompanyUser who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_audit_actions', to='core.companyuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_audit_logs', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='hr_agent_hr_company_dc0034_idx'), models.Index(fields=['target_type', 'target_id'], name='hr_agent_hr_target__134e88_idx'), models.Index(fields=['actor'], name='hr_agent_hr_actor_i_e9e66a_idx')],
            },
        ),
    ]
