# Generated by Django 5.2.13 on 2026-05-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_agent', '0009_audit_log_and_chunk_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('success_criteria', models.TextField(blank=True, default='', help_text='How "done" is judged (definition of done).')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('met', 'Met'), ('partially_met', 'Partially met'), ('missed', 'Missed'), ('dropped', 'Dropped')], default='open', max_length=20)),
                ('weight_pct', models.PositiveSmallIntegerField(default=0, help_text='Weighting toward the cycle score (0-100).')),
                ('target_value', models.CharField(blank=True, default='', help_text='Free-text target metric (e.g. "$50k ARR", "Ship v2").', max_length=80)),
                ('current_value', models.CharField(blank=True, default='', max_length=80)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, help_text='0-100. Manually updated or derived.')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Usually the manager who set the goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals_assigned', to='hr_agent.employee')),
                ('cycle', models.ForeignKey(blank=True, help_text='Optional — goal can exist outside a review cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='hr_agent.performancereviewcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='hr_agent.employee')),
                ('parent', models.ForeignKey(blank=True, help_text='Optional cascade: this goal supports a parent goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgoals', to='hr_agent.performancegoal')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_agent_pe_employe_fcdbfe_idx'), models.Index(fields=['cycle', 'status'], name='hr_agent_pe_cycle_i_74bb9f_idx'), models.Index(fields=['due_date'], name='hr_agent_pe_due_dat_e27ae8_idx')],
            },
        ),
    ]
