# Generated by Django 5.2.13 on 2026-05-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_merge_20260513_0857'),
        ('hr_agent', '0010_performance_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When PII on this row was scrubbed. Non-null = anonymized.', null=True),
        ),
        migrations.CreateModel(
            name='HRDocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', 'Read'), ('download', 'Download'), ('summarize', 'Summarize (LLM)'), ('extract', 'Extract fields (LLM)')], default='read', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_document_reads', to='core.companyuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_document_access_logs', to='core.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to='hr_agent.hrdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='hr_agent_hr_documen_0c5e72_idx'), models.Index(fields=['company', '-created_at'], name='hr_agent_hr_company_de422a_idx'), models.Index(fields=['actor', '-created_at'], name='hr_agent_hr_actor_i_d385af_idx')],
            },
        ),
    ]
