# Generated by Django 5.2.13 on 2026-05-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_agent', '0011_compliance_anonymize_and_doc_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='partial_day_period',
            field=models.CharField(blank=True, choices=[('', 'Full day'), ('morning', 'Morning (half-day)'), ('afternoon', 'Afternoon (half-day)'), ('hours', 'Specific hours')], default='', help_text='Empty for full-day. "morning"/"afternoon" = half-day. "hours" = use partial_hours.', max_length=12),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='partial_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used when partial_day_period="hours". Working hours requested (e.g. 2.5).', max_digits=4, null=True),
        ),
    ]
