# Generated by Django 5.2.13 on 2026-05-22 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_agent', '0012_partial_day_leave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hrdocument',
            name='is_outdated',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-deprecate: when True, this doc is excluded from retrieval.'),
        ),
        migrations.AddField(
            model_name='hrdocumentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='1-based PDF page this chunk came from. Null for non-PDF docs or chunks that span page breaks.', null=True),
        ),
        migrations.AddField(
            model_name='hrnotificationtemplate',
            name='quiet_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-template quiet-hours config. See model source for shape.'),
        ),
        migrations.AddField(
            model_name='hrworkflowexecution',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='hrnotificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('slack', 'Slack (webhook)'), ('teams', 'Microsoft Teams (webhook)')], default='email', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hrworkflowexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workflow', 'idempotency_key'), name='hr_workflow_exec_idem_uniq'),
        ),
    ]
