# Generated by Django 5.0.1 on 2025-12-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0004_jobdescription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobdescription',
            new_name='recruitment_is_acti_f9ddd4_idx',
            old_name='recruitment_is_acti_idx',
        ),
    ]
