# Generated by Django 5.0.1 on 2025-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0006_jobdescription_company_jobdescription_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='followup_count',
            field=models.IntegerField(default=0, help_text='Number of follow-up emails sent for unconfirmed interview'),
        ),
        migrations.AddField(
            model_name='interview',
            name='last_followup_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time a follow-up email was sent for unconfirmed interview', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='pre_interview_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the pre-interview reminder was sent', null=True),
        ),
    ]
