# Generated by Django 5.0.1 on 2025-12-30 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0007_interview_followup_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='followup_delay_hours',
            field=models.IntegerField(default=48, help_text='Hours to wait before sending first follow-up email for PENDING interviews'),
        ),
        migrations.AddField(
            model_name='interview',
            name='max_followup_emails',
            field=models.IntegerField(default=3, help_text='Maximum number of follow-up emails to send'),
        ),
        migrations.AddField(
            model_name='interview',
            name='min_hours_between_followups',
            field=models.IntegerField(default=24, help_text='Minimum hours between follow-up emails'),
        ),
        migrations.AddField(
            model_name='interview',
            name='reminder_hours_before',
            field=models.IntegerField(default=24, help_text='Hours before scheduled interview to send reminder email'),
        ),
        migrations.CreateModel(
            name='RecruiterEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_delay_hours', models.IntegerField(default=48, help_text='Hours to wait before sending first follow-up email for unconfirmed interviews')),
                ('min_hours_between_followups', models.IntegerField(default=24, help_text='Minimum hours between follow-up emails')),
                ('max_followup_emails', models.IntegerField(default=3, help_text='Maximum number of follow-up emails to send')),
                ('reminder_hours_before', models.IntegerField(default=24, help_text='Hours before scheduled interview to send reminder email')),
                ('auto_send_followups', models.BooleanField(default=True, help_text='Automatically send follow-up emails (if False, emails must be sent manually)')),
                ('auto_send_reminders', models.BooleanField(default=True, help_text='Automatically send pre-interview reminders (if False, reminders must be sent manually)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_email_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Email Settings',
                'verbose_name_plural': 'Recruiter Email Settings',
            },
        ),
    ]
