# Generated by Django 5.0.1 on 2026-01-09 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0011_change_hours_to_float'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterInterviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_from_date', models.DateField(blank=True, help_text='Start date from which interviews can be scheduled (leave empty to start from today)', null=True)),
                ('schedule_to_date', models.DateField(blank=True, help_text='End date until which interviews can be scheduled (leave empty for no end date)', null=True)),
                ('start_time', models.TimeField(default='09:00', help_text='Start time of day for interviews (e.g., 09:00 for 9 AM)')),
                ('end_time', models.TimeField(default='17:00', help_text='End time of day for interviews (e.g., 17:00 for 5 PM)')),
                ('interviews_per_day', models.IntegerField(default=3, help_text='Maximum number of interviews that can be scheduled per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interview_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Interview Settings',
                'verbose_name_plural': 'Recruiter Interview Settings',
            },
        ),
    ]
