# Generated by Django 5.0.1 on 2026-01-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0012_recruiterinterviewsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterinterviewsettings',
            name='interviews_per_day',
        ),
        migrations.AddField(
            model_name='recruiterinterviewsettings',
            name='interview_time_gap',
            field=models.IntegerField(default=30, help_text='Time gap between interview slots in minutes (e.g., 30 for 30 minutes)'),
        ),
    ]
