# Generated by Django 5.0.1 on 2026-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0013_remove_recruiterinterviewsettings_interviews_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterinterviewsettings',
            name='time_slots_json',
            field=models.JSONField(blank=True, default=list, help_text="Generated time slots stored as JSON array. Format: [{'date': 'YYYY-MM-DD', 'time': 'HH:MM', 'datetime': 'YYYY-MM-DDTHH:MM'}, ...]"),
        ),
    ]
