# Generated by Django 5.0.1 on 2026-01-22 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20260120_1821'),
        ('recruitment_agent', '0016_add_company_user_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterQualificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_threshold', models.IntegerField(default=65, help_text='Minimum confidence score (0-100) to mark candidate as INTERVIEW. Default: 65')),
                ('hold_threshold', models.IntegerField(default=45, help_text='Minimum confidence score (0-100) to mark candidate as HOLD. Default: 45. Scores below this are REJECTED.')),
                ('use_custom_thresholds', models.BooleanField(default=False, help_text='If True, use custom thresholds. If False, use default values (65 for INTERVIEW, 45 for HOLD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_qualification_settings_company', to='core.companyuser')),
                ('recruiter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_qualification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Qualification Settings',
                'verbose_name_plural': 'Recruiter Qualification Settings',
            },
        ),
    ]
