# Generated by Django 5.0.1 on 2026-01-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260122_2132'),
        ('recruitment_agent', '0017_recruiterqualificationsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterinterviewsettings',
            name='job',
            field=models.ForeignKey(blank=True, help_text='Job description this setting belongs to. If null, applies to all jobs (backward compatibility)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_settings', to='recruitment_agent.jobdescription'),
        ),
        migrations.AddConstraint(
            model_name='recruiterinterviewsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('company_user', 'job'), name='unique_company_user_job_settings'),
        ),
        migrations.AddConstraint(
            model_name='recruiterinterviewsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('recruiter', 'job'), name='unique_recruiter_job_settings'),
        ),
    ]
