# Generated by Django 5.0.1 on 2026-01-22 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20260122_2132'),
        ('recruitment_agent', '0018_recruiterinterviewsettings_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterinterviewsettings',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interview_settings_company', to='core.companyuser'),
        ),
        migrations.AlterField(
            model_name='recruiterinterviewsettings',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_interview_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='recruiterinterviewsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', True)), fields=('company_user',), name='unique_company_user_no_job_settings'),
        ),
    ]
