# Generated by Django 5.0.1 on 2026-02-06 21:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_update_userprofile_roles'),
        ('recruitment_agent', '0022_add_ppp_table_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentQAChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', help_text='Chat title (e.g. first question snippet)', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(help_text='Company user who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_qa_chats', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Recruitment QA Chat',
                'verbose_name_plural': 'Recruitment QA Chats',
                'db_table': 'ppp_recruitment_agent_recruitmentqachat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentQAChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('response_data', models.JSONField(blank=True, help_text='For assistant: full API response { answer, insights }', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruitment_agent.recruitmentqachat')),
            ],
            options={
                'verbose_name': 'Recruitment QA Chat Message',
                'verbose_name_plural': 'Recruitment QA Chat Messages',
                'db_table': 'ppp_recruitment_agent_recruitmentqachatmessage',
                'ordering': ['created_at'],
            },
        ),
    ]
