# Generated by Django 4.2.7 on 2026-02-05 08:49

from django.db import migrations


def rename_index_if_exists(apps, schema_editor):
    """Rename indexes only if they exist"""
    db_alias = schema_editor.connection.alias
    
    # Check and rename indexes for interview model
    with schema_editor.connection.cursor() as cursor:
        # Check if old index exists before renaming
        # Try both old and new table name formats
        index_renames = [
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'recruitment_status_210d1e_idx', 'ppp_recruit_status_f160a9_idx'),
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'recruitment_candida_1c227e_idx', 'ppp_recruit_candida_265a0e_idx'),
            (['recruitment_agent_jobdescription', 'ppp_recruitment_agent_jobdescription'], 'recruitment_is_acti_f9ddd4_idx', 'ppp_recruit_is_acti_0e877c_idx'),
        ]
        
        for table_names, old_name, new_name in index_renames:
            try:
                # Try each possible table name
                for table_name in table_names:
                    try:
                        # Check if index exists
                        cursor.execute("""
                            SELECT COUNT(*) 
                            FROM sys.indexes i
                            INNER JOIN sys.objects o ON i.object_id = o.object_id
                            WHERE o.name = ? AND i.name = ?
                        """, [table_name, old_name])
                        result = cursor.fetchone()
                        exists = result and result[0] > 0
                        
                        if exists:
                            # Rename the index
                            cursor.execute(f"""
                                EXEC sp_rename 
                                '{table_name}.{old_name}', 
                                '{new_name}', 
                                'INDEX'
                            """)
                            break  # Successfully renamed, move to next index
                    except Exception:
                        # Table doesn't exist with this name, try next
                        continue
            except Exception as e:
                # Index doesn't exist or already renamed, skip
                pass


def reverse_rename_index(apps, schema_editor):
    """Reverse the index rename"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        index_renames = [
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'ppp_recruit_status_f160a9_idx', 'recruitment_status_210d1e_idx'),
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'ppp_recruit_candida_265a0e_idx', 'recruitment_candida_1c227e_idx'),
            (['recruitment_agent_jobdescription', 'ppp_recruitment_agent_jobdescription'], 'ppp_recruit_is_acti_0e877c_idx', 'recruitment_is_acti_f9ddd4_idx'),
        ]
        
        for table_names, new_name, old_name in index_renames:
            try:
                for table_name in table_names:
                    try:
                        cursor.execute("""
                            SELECT COUNT(*) 
                            FROM sys.indexes i
                            INNER JOIN sys.objects o ON i.object_id = o.object_id
                            WHERE o.name = ? AND i.name = ?
                        """, [table_name, new_name])
                        result = cursor.fetchone()
                        exists = result and result[0] > 0
                        
                        if exists:
                            cursor.execute(f"""
                                EXEC sp_rename 
                                '{table_name}.{new_name}', 
                                '{old_name}', 
                                'INDEX'
                            """)
                            break
                    except Exception:
                        continue
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0022_add_ppp_table_prefix'),
    ]

def rename_tables_if_needed(apps, schema_editor):
    """Rename tables only if they exist with old names"""
    with schema_editor.connection.cursor() as cursor:
        table_renames = [
            ('recruitment_agent_careerapplication', 'ppp_recruitment_agent_careerapplication'),
            ('recruitment_agent_cvrecord', 'ppp_recruitment_agent_cvrecord'),
            ('recruitment_agent_interview', 'ppp_recruitment_agent_interview'),
            ('recruitment_agent_jobdescription', 'ppp_recruitment_agent_jobdescription'),
            ('recruitment_agent_recruiteremailsettings', 'ppp_recruitment_agent_recruiteremailsettings'),
            ('recruitment_agent_recruiterinterviewsettings', 'ppp_recruitment_agent_recruiterinterviewsettings'),
            ('recruitment_agent_recruiterqualificationsettings', 'ppp_recruitment_agent_recruiterqualificationsettings'),
        ]
        
        for old_name, new_name in table_renames:
            try:
                # Check if old table exists
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM sys.tables 
                    WHERE name = ?
                """, [old_name])
                result = cursor.fetchone()
                old_exists = result and result[0] > 0
                
                # Check if new table already exists
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM sys.tables 
                    WHERE name = ?
                """, [new_name])
                result = cursor.fetchone()
                new_exists = result and result[0] > 0
                
                if old_exists and not new_exists:
                    # Rename the table
                    cursor.execute(f"""
                        EXEC sp_rename 
                        '{old_name}', 
                        '{new_name}'
                    """)
            except Exception:
                # Table doesn't exist or already renamed, skip
                pass


def reverse_rename_tables(apps, schema_editor):
    """Reverse the table rename"""
    with schema_editor.connection.cursor() as cursor:
        table_renames = [
            ('ppp_recruitment_agent_careerapplication', 'recruitment_agent_careerapplication'),
            ('ppp_recruitment_agent_cvrecord', 'recruitment_agent_cvrecord'),
            ('ppp_recruitment_agent_interview', 'recruitment_agent_interview'),
            ('ppp_recruitment_agent_jobdescription', 'recruitment_agent_jobdescription'),
            ('ppp_recruitment_agent_recruiteremailsettings', 'recruitment_agent_recruiteremailsettings'),
            ('ppp_recruitment_agent_recruiterinterviewsettings', 'recruitment_agent_recruiterinterviewsettings'),
            ('ppp_recruitment_agent_recruiterqualificationsettings', 'recruitment_agent_recruiterqualificationsettings'),
        ]
        
        for new_name, old_name in table_renames:
            try:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM sys.tables 
                    WHERE name = ?
                """, [new_name])
                result = cursor.fetchone()
                exists = result and result[0] > 0
                
                if exists:
                    cursor.execute(f"""
                        EXEC sp_rename 
                        '{new_name}', 
                        '{old_name}'
                    """)
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0022_add_ppp_table_prefix'),
    ]

    operations = [
        migrations.RunPython(rename_index_if_exists, reverse_rename_index),
        migrations.RunPython(rename_tables_if_needed, reverse_rename_tables),
        # Note: AlterModelTable operations removed - table renames handled manually above
        # Django will use the table names from model Meta classes
    ]
