# Generated by Django 4.2.7 on 2026-02-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0023_add_recruitment_qa_chat'),
        ('recruitment_agent', '0023_rename_recruitment_status_210d1e_idx_ppp_recruit_status_f160a9_idx_and_more'),
    ]

    operations = [
    ]
