# Generated by Django 4.2.7 on 2026-02-18 03:05
# Fixed for SQL Server: use conditional index/table renames so migration does not fail
# when indexes or tables were already renamed (e.g. by 0023) or do not exist.

from django.db import migrations


def safe_rename_indexes(apps, schema_editor):
    """Rename indexes only if the old index exists; skip if already renamed or missing."""
    with schema_editor.connection.cursor() as cursor:
        index_renames = [
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'recruitment_status_210d1e_idx', 'ppp_recruit_status_f160a9_idx'),
            (['recruitment_agent_interview', 'ppp_recruitment_agent_interview'], 'recruitment_candida_1c227e_idx', 'ppp_recruit_candida_265a0e_idx'),
            (['recruitment_agent_jobdescription', 'ppp_recruitment_agent_jobdescription'], 'recruitment_is_acti_f9ddd4_idx', 'ppp_recruit_is_acti_0e877c_idx'),
        ]
        for table_names, old_name, new_name in index_renames:
            try:
                for table_name in table_names:
                    try:
                        cursor.execute("""
                            SELECT COUNT(*) FROM sys.indexes i
                            INNER JOIN sys.objects o ON i.object_id = o.object_id
                            WHERE o.name = ? AND i.name = ?
                        """, [table_name, old_name])
                        row = cursor.fetchone()
                        if row and row[0] > 0:
                            cursor.execute(
                                "EXEC sp_rename '{}', '{}', 'INDEX'".format(
                                    f'{table_name}.{old_name}', new_name
                                )
                            )
                            break
                    except Exception:
                        continue
            except Exception:
                pass


def safe_rename_tables(apps, schema_editor):
    """Rename tables only if old name exists and new name does not; skip otherwise."""
    with schema_editor.connection.cursor() as cursor:
        table_renames = [
            ('recruitment_agent_careerapplication', 'ppp_recruitment_agent_careerapplication'),
            ('recruitment_agent_cvrecord', 'ppp_recruitment_agent_cvrecord'),
            ('recruitment_agent_interview', 'ppp_recruitment_agent_interview'),
            ('recruitment_agent_jobdescription', 'ppp_recruitment_agent_jobdescription'),
            ('recruitment_agent_recruiteremailsettings', 'ppp_recruitment_agent_recruiteremailsettings'),
            ('recruitment_agent_recruiterinterviewsettings', 'ppp_recruitment_agent_recruiterinterviewsettings'),
            ('recruitment_agent_recruiterqualificationsettings', 'ppp_recruitment_agent_recruiterqualificationsettings'),
        ]
        for old_name, new_name in table_renames:
            try:
                cursor.execute("SELECT COUNT(*) FROM sys.tables WHERE name = ?", [old_name])
                r1 = cursor.fetchone()
                old_exists = r1 and r1[0] > 0
                cursor.execute("SELECT COUNT(*) FROM sys.tables WHERE name = ?", [new_name])
                r2 = cursor.fetchone()
                new_exists = r2 and r2[0] > 0
                if old_exists and not new_exists:
                    cursor.execute("EXEC sp_rename ?, ?", [old_name, new_name])
            except Exception:
                pass


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0024_merge_20260213_0020'),
    ]

    operations = [
        migrations.RunPython(safe_rename_indexes, noop_reverse),
        migrations.RunPython(safe_rename_tables, noop_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='interview',
                    new_name='ppp_recruit_status_f160a9_idx',
                    old_name='recruitment_status_210d1e_idx',
                ),
                migrations.RenameIndex(
                    model_name='interview',
                    new_name='ppp_recruit_candida_265a0e_idx',
                    old_name='recruitment_candida_1c227e_idx',
                ),
                migrations.RenameIndex(
                    model_name='jobdescription',
                    new_name='ppp_recruit_is_acti_0e877c_idx',
                    old_name='recruitment_is_acti_f9ddd4_idx',
                ),
                migrations.AlterModelTable(
                    name='careerapplication',
                    table='ppp_recruitment_agent_careerapplication',
                ),
                migrations.AlterModelTable(
                    name='cvrecord',
                    table='ppp_recruitment_agent_cvrecord',
                ),
                migrations.AlterModelTable(
                    name='interview',
                    table='ppp_recruitment_agent_interview',
                ),
                migrations.AlterModelTable(
                    name='jobdescription',
                    table='ppp_recruitment_agent_jobdescription',
                ),
                migrations.AlterModelTable(
                    name='recruiteremailsettings',
                    table='ppp_recruitment_agent_recruiteremailsettings',
                ),
                migrations.AlterModelTable(
                    name='recruiterinterviewsettings',
                    table='ppp_recruitment_agent_recruiterinterviewsettings',
                ),
                migrations.AlterModelTable(
                    name='recruiterqualificationsettings',
                    table='ppp_recruitment_agent_recruiterqualificationsettings',
                ),
            ],
        ),
    ]
