# Generated by Django 5.0.1 on 2026-02-19 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_frontline_agent_module'),
        ('recruitment_agent', '0025_rename_recruitment_status_210d1e_idx_ppp_recruit_status_f160a9_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGraphPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='User-friendly title for the prompt', max_length=255)),
                ('prompt', models.TextField(help_text='The natural language prompt for graph generation')),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('line', 'Line Chart'), ('area', 'Area Chart'), ('scatter', 'Scatter Plot'), ('heatmap', 'Heat Map')], default='bar', help_text='Type of chart this prompt generates', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorizing and searching prompts')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this prompt is marked as favorite')),
                ('run_count', models.IntegerField(default=0, help_text='Number of times this prompt has been run')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last time this prompt was executed', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(help_text='Company user who saved this prompt', on_delete=django.db.models.deletion.CASCADE, related_name='saved_graph_prompts', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Saved Graph Prompt',
                'verbose_name_plural': 'Saved Graph Prompts',
                'db_table': 'ppp_recruitment_agent_savedgraphprompt',
                'ordering': ['-is_favorite', '-updated_at'],
                'indexes': [models.Index(fields=['company_user', 'is_favorite'], name='ppp_recruit_company_c37794_idx'), models.Index(fields=['company_user', '-created_at'], name='ppp_recruit_company_f0da44_idx')],
            },
        ),
    ]
