# Generated by Django 5.0.1 on 2026-06-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0028_jobapplication_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='application_close_date',
            field=models.DateField(blank=True, help_text='Deadline date after which applications are no longer accepted', null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='application_open_date',
            field=models.DateField(blank=True, help_text='Date from which applications are accepted', null=True),
        ),
    ]
