# Generated by Django 5.0.1 on 2026-06-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0029_job_application_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='feedback_improvements',
            field=models.TextField(blank=True, help_text='Areas for improvement', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_notes',
            field=models.TextField(blank=True, help_text='General feedback notes', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_rating',
            field=models.IntegerField(blank=True, help_text='Interviewer rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_strengths',
            field=models.TextField(blank=True, help_text='Candidate strengths observed', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When interviewer submitted feedback', null=True),
        ),
    ]
