# Generated by Django 4.2.10 on 2026-06-28 13:43

from django.db import migrations, models
import recruitment_agent.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0034_interview_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvrecorddecisionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment_agent.models._cv_upload_to),
        ),
    ]
