# Generated by Django 5.0.1 on 2026-06-29 18:07

import django.core.validators
import recruitment_agent.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_add_indexes_validators_clean'),
        ('recruitment_agent', '0034_interview_meeting_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvrecorddecisionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=recruitment_agent.models._cv_upload_to),
        ),
        migrations.AlterField(
            model_name='recruiterinterviewsettings',
            name='interview_time_gap',
            field=models.IntegerField(default=30, help_text='Time gap between interview slots in minutes (15–480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AddIndex(
            model_name='cvrecord',
            index=models.Index(fields=['qualification_decision', '-created_at'], name='ppp_recruit_qualifi_f6344d_idx'),
        ),
        migrations.AddIndex(
            model_name='cvrecord',
            index=models.Index(fields=['job_description', '-created_at'], name='ppp_recruit_job_des_96832c_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', '-created_at'], name='ppp_recruit_status_a9d3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['candidate_email', 'status'], name='ppp_recruit_candida_d15479_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['company_user', 'status'], name='ppp_recruit_company_02b4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterinterviewsettings',
            index=models.Index(fields=['company_user', 'job'], name='ppp_recruit_company_32da28_idx'),
        ),
        migrations.AddIndex(
            model_name='recruiterinterviewsettings',
            index=models.Index(fields=['recruiter', 'job'], name='ppp_recruit_recruit_968aad_idx'),
        ),
    ]
