# Generated by Django 4.2.10 on 2026-07-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0035_alter_cvrecorddecisionlog_id_and_more'),
        ('recruitment_agent', '0037_jobapplication_access_token'),
    ]

    operations = [
    ]
