# Generated by Django 5.2.13 on 2026-07-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0037_merge_20260706_1855'),
        ('recruitment_agent', '0038_merge_20260707_0042'),
    ]

    operations = [
    ]
