# Generated by Django 4.2.10 on 2026-07-15 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_agent', '0039_merge_20260708_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvrecord',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_records', to='recruitment_agent.jobapplication'),
        ),
        migrations.AddConstraint(
            model_name='cvrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('job_application__isnull', False)), fields=('job_application',), name='uq_cvrecord_job_application_notnull'),
        ),
    ]
