# Generated by Django 4.2.10 on 2026-09-30 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment_agent', '0040_alter_cvrecord_job_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewers',
            field=models.ManyToManyField(blank=True, help_text='Employee logins interviewing alongside the recruiter.', related_name='recruitment_interviews_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='timezone_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='recruiterinterviewsettings',
            name='timezone_name',
            field=models.CharField(blank=True, default='', help_text="IANA timezone the recruiter's interview times are in, e.g. Asia/Karachi.", max_length=64),
        ),
    ]
