# Generated by Django 4.2.10 on 2026-09-30 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_agent', '0017_accrual_runs_and_balance_merge'),
        ('recruitment_agent', '0041_interview_duration_timezone_interviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='hr_employee',
            field=models.ForeignKey(blank=True, help_text='HR employee record created from this hire.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviews', to='hr_agent.employee'),
        ),
    ]
