# Generated by Django 4.2.10 on 2026-04-21 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing_agent', '0029_add_qa_research_chat_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_subject', models.CharField(help_text='AI-generated subject', max_length=500)),
                ('draft_body', models.TextField(help_text='AI-generated body')),
                ('edited_subject', models.CharField(blank=True, help_text='User-edited subject (overrides draft)', max_length=500)),
                ('edited_body', models.TextField(blank=True, help_text='User-edited body (overrides draft)')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('formal', 'Formal'), ('casual', 'Casual'), ('apologetic', 'Apologetic'), ('confident', 'Confident'), ('empathetic', 'Empathetic')], default='professional', max_length=20)),
                ('ai_notes', models.TextField(blank=True, help_text='AI reasoning / notes about the draft')),
                ('generation_prompt', models.TextField(blank=True, help_text='Extra instructions the user provided')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('failed', 'Send Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_error', models.TextField(blank=True)),
                ('regeneration_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(blank=True, help_text='Which account to send from. Defaults to the user default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_drafts', to='marketing_agent.emailaccount')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_drafts', to='marketing_agent.lead')),
                ('original_email', models.ForeignKey(help_text='The incoming email that this draft is replying to', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='marketing_agent.reply')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_drafts', to=settings.AUTH_USER_MODEL)),
                ('parent_draft', models.ForeignKey(blank=True, help_text='The previous draft this one replaced (when regenerated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='reply_draft_agent.replydraft')),
                ('sent_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_drafts', to='marketing_agent.emailsendhistory')),
            ],
            options={
                'db_table': 'ppp_replydraftagent_replydraft',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-created_at'], name='ppp_replydr_owner_i_0a8319_idx'), models.Index(fields=['original_email', '-created_at'], name='ppp_replydr_origina_fc6b48_idx')],
            },
        ),
    ]
