# Generated by Django 4.2.10 on 2026-04-22 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0029_add_qa_research_chat_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reply_draft_agent', '0001_initial'),
    ]

    operations = [
        # MSSQL driver introspects every model-level index during ALTER FIELD
        # and chokes on any ordering-prefixed column ('-created_at'). Drop
        # both composite indexes, alter the field, then re-add the indexes.
        migrations.RemoveIndex(
            model_name='replydraft',
            name='ppp_replydr_owner_i_0a8319_idx',
        ),
        migrations.RemoveIndex(
            model_name='replydraft',
            name='ppp_replydr_origina_fc6b48_idx',
        ),
        migrations.AlterField(
            model_name='replydraft',
            name='original_email',
            field=models.ForeignKey(blank=True, help_text='The campaign reply this draft is replying to (exactly one of original_email / inbox_email is set)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='marketing_agent.reply'),
        ),
        migrations.AddIndex(
            model_name='replydraft',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='ppp_replydr_owner_i_0a8319_idx'),
        ),
        migrations.AddIndex(
            model_name='replydraft',
            index=models.Index(fields=['original_email', '-created_at'], name='ppp_replydr_origina_fc6b48_idx'),
        ),
        migrations.CreateModel(
            name='InboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='RFC Message-ID header (dedupe key)', max_length=500)),
                ('in_reply_to', models.CharField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True)),
                ('from_email', models.EmailField(db_index=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date header from the message, or sync time as fallback')),
                ('interest_level', models.CharField(choices=[('positive', 'Positive/Interested'), ('negative', 'Negative/Not Interested'), ('neutral', 'Neutral'), ('requested_info', 'Requested More Information'), ('objection', 'Has Objection/Concern'), ('unsubscribe', 'Unsubscribe Request'), ('not_analyzed', 'Not Analyzed')], default='not_analyzed', max_length=20)),
                ('analysis', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_account', models.ForeignKey(help_text='Mailbox this message arrived in', on_delete=django.db.models.deletion.CASCADE, related_name='inbox_emails', to='marketing_agent.emailaccount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ppp_replydraftagent_inboxemail',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='replydraft',
            name='inbox_email',
            field=models.ForeignKey(blank=True, help_text='The generic inbox email this draft is replying to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='reply_draft_agent.inboxemail'),
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['owner', '-received_at'], name='ppp_replydr_owner_i_a7f4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['email_account', '-received_at'], name='ppp_replydr_email_a_07c73e_idx'),
        ),
        migrations.AddIndex(
            model_name='inboxemail',
            index=models.Index(fields=['from_email'], name='ppp_replydr_from_em_0ab0fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inboxemail',
            unique_together={('email_account', 'message_id')},
        ),
    ]
