# Generated by Django 4.2.10 on 2026-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_draft_agent', '0003_inboxemail_direction_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxemail',
            name='body_html',
            field=models.TextField(blank=True, help_text='Original HTML body if the source carried one. Rendered in the UI for fidelity (links, images, layout); plain `body` is used as fallback when this is empty.'),
        ),
        migrations.AlterField(
            model_name='inboxemail',
            name='body',
            field=models.TextField(blank=True, help_text='Plain-text body. Used for AI analysis and search; preferred over HTML when both are present in the source.'),
        ),
    ]
