# Generated by Django 4.2.10 on 2026-04-28 20:27

from django.db import migrations, models
import django.db.models.deletion
import reply_draft_agent.models


class Migration(migrations.Migration):

    dependencies = [
        ('reply_draft_agent', '0005_alter_inboxemail_body_alter_inboxemail_body_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename from the message part.', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('file', models.FileField(help_text='Stored via default_storage (local FS now, S3 later).', max_length=1000, upload_to=reply_draft_agent.models._inbox_attachment_upload_path)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', help_text='Content hash. Lets us dedupe identical files across emails.', max_length=64)),
                ('content_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('is_inline', models.BooleanField(default=False, help_text='True for cid: parts referenced inside body_html (e.g. inline images).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inbox_email', models.ForeignKey(help_text='Email this attachment was extracted from. CASCADE keeps the table consistent when emails are pruned; the actual file is removed by the post_delete signal wired up in apps.py.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reply_draft_agent.inboxemail')),
            ],
            options={
                'db_table': 'ppp_replydraftagent_inboxattachment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['inbox_email', 'created_at'], name='ppp_replydr_inbox_e_bbfbd7_idx')],
            },
        ),
    ]
