# Generated by Django 4.2.10 on 2026-05-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply_draft_agent', '0011_replydraft_attempted_message_ids'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inboxemail',
            new_name='ppp_replydr_email_a_0867cd_idx',
            old_name='ppp_rda_inboxemail_acct_thread_idx',
        ),
    ]
