# Generated by Django 4.2.10 on 2026-06-23 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0082_merge_20260609_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecCalendarChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_calendar_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecDocumentChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_document_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecMeetingSchedulingChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_scheduling_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecNotetakerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_notetaker_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecNotificationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_notification_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecTaskChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_task_chats', to='core.companyuser')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('agenda', models.JSONField(blank=True, default=list, help_text='List of agenda items')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_link', models.URLField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_confirmation', 'Pending Confirmation')], db_index=True, default='scheduled', max_length=30)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_organized_meetings', to='core.companyuser')),
                ('parent_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='meeting_agent.executivemeeting')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField(blank=True, default='', help_text='Raw transcript submitted by user')),
                ('ai_summary', models.TextField(blank=True, default='', help_text='AI-generated meeting summary')),
                ('key_decisions', models.JSONField(blank=True, default=list, help_text='List of key decisions made')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='meeting_agent.executivemeeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('agenda', 'Agenda'), ('minutes', 'Minutes'), ('briefing', 'Briefing'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Document body (markdown)')),
                ('ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_meeting_documents', to='core.companyuser')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='meeting_agent.executivemeeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('ai_extracted', models.BooleanField(default=False, help_text='True if extracted by AI from transcript')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exec_action_items', to='core.companyuser')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='meeting_agent.executivemeeting')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ExecTaskChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.exectaskchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecNotificationChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.execnotificationchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecNotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams')], max_length=20)),
                ('target', models.CharField(help_text='Email address or webhook URL', max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('severities', models.CharField(blank=True, default='', help_text='Comma-separated severities to send. Empty = all.', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_notification_channels', to='core.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='ExecNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('meeting_reminder', 'Meeting Reminder'), ('meeting_invite', 'Meeting Invite'), ('meeting_update', 'Meeting Update'), ('meeting_cancelled', 'Meeting Cancelled'), ('action_item_due', 'Action Item Due'), ('action_item_overdue', 'Action Item Overdue'), ('task_due', 'Task Due'), ('task_overdue', 'Task Overdue'), ('calendar_conflict', 'Calendar Conflict'), ('participant_response', 'Participant Response'), ('document_ready', 'Document Ready')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Extra context — meeting_id, task_id, etc.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_notifications', to='core.companyuser')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='meeting_agent.executivemeeting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecNotetakerChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.execnotetakerchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecMeetingSchedulingChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.execmeetingschedulingchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecDocumentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.execdocumentchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecCalendarChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meeting_agent.execcalendarchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked')], db_index=True, default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ai_reasoning', models.TextField(blank=True, default='', help_text='AI explanation for priority assignment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_tasks', to='core.companyuser')),
                ('linked_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='meeting_agent.executivemeeting')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
                'indexes': [models.Index(fields=['company_user', 'status'], name='meeting_age_company_e7e9dc_idx'), models.Index(fields=['company_user', '-priority'], name='meeting_age_company_04b78b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveMeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('counter_proposed', 'Counter Proposed'), ('tentative', 'Tentative')], db_index=True, default='pending', max_length=20)),
                ('counter_proposed_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_meeting_participations', to='core.companyuser')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meeting_agent.executivemeeting')),
            ],
            options={
                'unique_together': {('meeting', 'company_user')},
            },
        ),
        migrations.AddIndex(
            model_name='executivemeeting',
            index=models.Index(fields=['organizer', '-scheduled_at'], name='meeting_age_organiz_6c3959_idx'),
        ),
        migrations.AddIndex(
            model_name='executivemeeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='meeting_age_status_4d1bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='exectaskchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_05b646_idx'),
        ),
        migrations.AddIndex(
            model_name='execnotificationchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_8e75eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='execnotificationchannel',
            unique_together={('company_user', 'channel_type', 'target')},
        ),
        migrations.AddIndex(
            model_name='execnotification',
            index=models.Index(fields=['company_user', 'is_read', '-created_at'], name='meeting_age_company_a555b1_idx'),
        ),
        migrations.AddIndex(
            model_name='execnotetakerchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_7fdf22_idx'),
        ),
        migrations.AddIndex(
            model_name='execmeetingschedulingchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_f98df6_idx'),
        ),
        migrations.AddIndex(
            model_name='execdocumentchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_6a0ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='execcalendarchat',
            index=models.Index(fields=['company_user', '-updated_at'], name='meeting_age_company_c75e02_idx'),
        ),
    ]
