# Generated by Django 4.2.10 on 2026-06-28 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_adminpricingconfig_agent_name_and_more'),
        ('meeting_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecStandaloneDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('agenda', 'Agenda'), ('minutes', 'Minutes'), ('briefing', 'Briefing'), ('report', 'Report'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Document body (markdown)')),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exec_standalone_documents', to='core.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
