# Generated by Django 4.2.10 on 2026-06-30 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_adminpricingconfig_agent_name_and_more'),
        ('meeting_agent', '0002_add_exec_standalone_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivetask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exec_assigned_tasks', to='core.companyuser'),
        ),
    ]
