# Generated by Django 4.2.10 on 2026-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_adminpricingconfig_agent_name_and_more'),
        ('meeting_agent', '0003_add_assignee_to_executive_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivetask',
            name='assignee',
        ),
        migrations.AddField(
            model_name='executivetask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='exec_assigned_tasks', to='core.companyuser'),
        ),
    ]
