# Generated by Django 4.2.10 on 2026-06-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_agent', '0004_assignee_fk_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivemeeting',
            name='location',
        ),
    ]
