# Generated by Django 4.2.10 on 2026-07-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_agent', '0005_remove_location_from_executivemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivetask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='meeting_agent.executivetask'),
        ),
    ]
