# Generated by Django 4.2.10 on 2026-07-14 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_agent', '0006_executivetask_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivetask',
            name='source_action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_tasks', to='meeting_agent.meetingactionitem'),
        ),
    ]
