# Generated by Django 4.2.10 on 2026-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_agent', '0008_downgrade_critical_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='execstandalonedocument',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Generated without a linked meeting — a fill-in template, not from real meeting data.'),
        ),
    ]
