# Generated by Django 4.2.10 on 2026-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0004_campaign_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdrmeeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
