# Generated by Django 5.2.13 on 2026-05-21 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0005_alter_sdrmeeting_id'),
        ('ai_sdr_agent', '0006_meeting_booking_token'),
    ]

    operations = [
    ]
