# Generated by Django 4.2.10 on 2026-05-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0005_alter_sdrmeeting_id'),
        ('ai_sdr_agent', '0006_meeting_booking_token'),
    ]

    operations = [
    ]
