# Generated by Django 5.2.13 on 2026-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0007_merge_20260521_0030'),
        ('ai_sdr_agent', '0007_merge_20260521_0934'),
    ]

    operations = [
    ]
