# Generated by Django 5.0.1 on 2026-05-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0005_alter_sdrmeeting_id'),
        ('ai_sdr_agent', '0007_sdrmeeting_enrollment_unique'),
    ]

    operations = [
    ]
