# Generated by Django 4.2.10 on 2026-05-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0008_merge_20260516_0125'),
        ('ai_sdr_agent', '0008_merge_20260522_0841'),
    ]

    operations = [
    ]
