# Generated by Django 5.0.1 on 2026-05-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0007_merge_20260521_0030'),
        ('ai_sdr_agent', '0007_merge_20260521_0934'),
        ('ai_sdr_agent', '0008_merge_20260516_0125'),
    ]

    operations = [
    ]
