# Generated by Django 5.0.1 on 2026-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0009_merge_20260525_0145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sdrmeeting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='email_bounce_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='email_bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='email_bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
