# Generated by Django 5.0.1 on 2026-05-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0010_add_lead_email_bounce_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrmeeting',
            name='lead_timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
    ]
