# Generated by Django 5.0.1 on 2026-05-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0008_merge_20260522_0841'),
        ('ai_sdr_agent', '0012_sdragentsettings'),
    ]

    operations = [
    ]
