# Generated by Django 4.2.10 on 2026-06-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0009_merge_20260526_0153'),
        ('ai_sdr_agent', '0013_merge_0008_merge_20260522_0841_0012_sdragentsettings'),
    ]

    operations = [
    ]
