# Generated by Django 4.2.10 on 2026-06-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0014_merge_20260603_0005'),
        ('ai_sdr_agent', '0014_merge_20260603_0545'),
    ]

    operations = [
    ]
