# Generated by Django 5.0.1 on 2026-06-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0014_merge_20260603_0005'),
        ('ai_sdr_agent', '0014_merge_20260603_0545'),
    ]

    operations = [
    ]
