# Generated by Django 5.0.1 on 2026-06-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0015_merge_20260604_2320'),
        ('ai_sdr_agent', '0017_add_lead_quality_fields'),
    ]

    operations = [
    ]
