# Generated by Django 4.2.10 on 2026-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0018_merge_20260613_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdricpprofile',
            name='hot_threshold',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='sdricpprofile',
            name='warm_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='sdrlead',
            name='outreach_strategy',
            field=models.TextField(blank=True),
        ),
    ]
