# Generated by Django 4.2.10 on 2026-08-04 17:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0019_alter_sdricpprofile_hot_threshold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdrlead',
            options={'base_manager_name': 'all_objects', 'ordering': ['-score', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='sdrlead',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
