# Generated by Django 4.2.10 on 2026-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0020_alter_sdrlead_options_alter_sdrlead_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdrlead',
            name='qualification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='qualification_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='qualification_queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sdrlead',
            name='qualification_status',
            field=models.CharField(choices=[('none', 'Not queued'), ('pending', 'Queued'), ('processing', 'Processing'), ('done', 'Qualified'), ('failed', 'Failed')], db_index=True, default='none', max_length=12),
        ),
    ]
