# Generated by Django 4.2.10 on 2026-08-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_sdr_agent', '0021_sdrlead_qualification_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdrlead',
            name='source',
            field=models.CharField(choices=[('apollo', 'Apollo.io'), ('apify', 'Apify'), ('manual', 'Manual'), ('csv_import', 'CSV Import'), ('ai_generated', 'AI Generated')], default='manual', max_length=30),
        ),
    ]
