// tests/agents/PM_Agent/createTask.spec.js
const { test, expect } = require('@playwright/test');

const { setupDOMSweeper } = require('../../helper/auth');

test.describe('Project Manager Agent - Create Task Module', () => {

  test.beforeEach(async ({ page }) => {
    // 1. Setup the DOM sweeper to handle tours automatically
    await setupDOMSweeper(page);

    // 2. Open Dashboard directly (uses pre-authenticated storageState)
    await page.goto('http://localhost:3000/project-manager/dashboard', { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1000);

    // 3. Click "+ Create Task" tab
    const createTaskTab = page.locator('[role="tab"]').filter({ hasText: 'Create Task' }).first();
    await createTaskTab.click({ force: true });

    // 4. Ensure the Create Task form is loaded and visible
    await expect(page.getByText('Create Task Manually')).toBeVisible({ timeout: 15000 });
  });

  // --- POSITIVE PATH ---
  test('POS-01: Should successfully create a new task with valid details', async ({ page }) => {
    // 1. Select a Project (handles custom React/Radix select menus)
    const projectDropdown = page.locator('button').filter({ hasText: 'Select a project' }).first();
    await expect(projectDropdown).toBeVisible({ timeout: 5000 });
    await projectDropdown.click();
    await page.waitForTimeout(500);

    // Click the first available option in the dropdown list
    const firstOption = page.locator('[role="option"], [role="menuitem"], li').first();
    await firstOption.click({ force: true });
    await page.waitForTimeout(300);

    // 2. Fill in Task Title and Description
    const uniqueTaskTitle = `Automated Test Task ${Date.now()}`;
    await page.getByPlaceholder('Enter task title').fill(uniqueTaskTitle);
    await page.getByPlaceholder('Enter task description').fill('Automated task description generated by E2E test runner.');

    // 3. Fill in Estimated Hours (targets placeholder or number input)
    const estimatedHoursInput = page.locator('input[type="number"]').or(page.getByPlaceholder('0.0'));
    if (await estimatedHoursInput.isVisible()) {
      await estimatedHoursInput.fill('8');
    }

    // 4. Click "+ Create Task" Submit Button
    const submitBtn = page.locator('button').filter({ hasText: 'Create Task' }).last();
    await submitBtn.click({ force: true });

    await page.waitForTimeout(1000);
  });

  // --- NEGATIVE PATHS ---
  test('NEG-01: Should block task creation when all required fields are blank', async ({ page }) => {
    const submitBtn = page.locator('button').filter({ hasText: 'Create Task' }).last();
    await submitBtn.click({ force: true });

    // Verify form remains on screen
    await expect(page.getByText('Create Task Manually')).toBeVisible();
  });

  test('NEG-02: Should block task creation when Task Title is blank but Project is selected', async ({ page }) => {
    // Select project
    const projectDropdown = page.locator('button').filter({ hasText: 'Select a project' }).first();
    await projectDropdown.click();
    await page.waitForTimeout(500);
    await page.locator('[role="option"], [role="menuitem"], li').first().click({ force: true });

    // Click submit with blank Title
    const submitBtn = page.locator('button').filter({ hasText: 'Create Task' }).last();
    await submitBtn.click({ force: true });

    // Verify form remains on screen
    await expect(page.getByText('Create Task Manually')).toBeVisible();
  });

  // --- EDGE CASE ---
  test('EDGE-01: Should allow selecting a deadline', async ({ page }) => {
    const deadlineBtn = page.getByText('Pick a deadline').first();
    if (await deadlineBtn.isVisible().catch(() => false)) {
      await deadlineBtn.click({ force: true });
      await page.waitForTimeout(500);
    }
  });

});