# """
# Django settings for project_manager_ai project.

# Generated by 'django-admin startproject' using Django 5.0.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """

# from pathlib import Path
# import os
# from dotenv import load_dotenv

# # Load environment variables from .env file
# load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-9hce6%w7!*)lb#$^6)gb8!h01#6t6y_85nn=exz82l4dj=6q45'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'core',
#     'project_manager_agent',
#     'recruitment_agent',
#     'marketing_agent.apps.MarketingAgentConfig',  # Use app config for agent registration
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'project_manager_ai.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Global templates folder,
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'project_manager_ai.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# # SQL Server Database Configuration
# # Set USE_SQL_SERVER=True in .env to use SQL Server, otherwise uses SQLite
# USE_SQL_SERVER = os.getenv('USE_SQL_SERVER', 'False').lower() == 'true'

# if USE_SQL_SERVER:
#     # Check if using Windows Authentication (Integrated Security)
#     USE_WINDOWS_AUTH = os.getenv('USE_WINDOWS_AUTH', 'False').lower() == 'true'
    
#     # Configure database settings for mssql-django (supports SQL Server 2022)
#     db_config = {
#         'ENGINE': 'mssql',
#         'NAME': os.getenv('DB_NAME', ''),
#         'HOST': os.getenv('DB_HOST', 'localhost'),
#         'PORT': os.getenv('DB_PORT', '1433'),
#         'OPTIONS': {
#             'driver': os.getenv('DB_DRIVER', 'ODBC Driver 17 for SQL Server'),  # or 'ODBC Driver 18 for SQL Server'
#             'extra_params': 'TrustServerCertificate=yes',  # Remove this in production with proper SSL
#         },
#     }
    
#     if USE_WINDOWS_AUTH:
#         # Windows Authentication - add Trusted_Connection
#         db_config['OPTIONS']['extra_params'] = 'Trusted_Connection=yes;TrustServerCertificate=yes'
#     else:
#         # SQL Server Authentication - use username and password
#         db_config['USER'] = os.getenv('DB_USER', '')
#         db_config['PASSWORD'] = os.getenv('DB_PASSWORD', '')
    
#     DATABASES = {
#         'default': db_config
#     }
# else:
#     # Default SQLite database (for development)
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#         }
#     }


# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]



# # Default primary key field type
# # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# # Auth settings
# LOGIN_REDIRECT_URL = '/dashboard/'  # After login, go to dashboard
# LOGOUT_REDIRECT_URL = '/'  # After logout, go to home
# LOGIN_URL = '/login/'  # Redirect unauth users here

# # Groq API Settings (for project manager agents and marketing Q&A agent)
# GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
# GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')  # Default model (used for Q&A)

# # OpenAI API Settings (for Marketing Agents - for document writing and advanced tasks)
# OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
# OPENAI_MODEL = os.getenv('OPENAI_MODEL', 'gpt-4.1')  # Default model (or gpt-4.1 if available)
# OPENAI_REASONING_MODEL = os.getenv('OPENAI_REASONING_MODEL', 'gpt-4.1')  # For advanced reasoning
# OPENAI_WRITING_MODEL = os.getenv('OPENAI_WRITING_MODEL', 'gpt-4.1')  # For document writing
# OPENAI_EMBEDDING_MODEL = os.getenv('OPENAI_EMBEDDING_MODEL', 'text-embedding-3-large')  # For RAG/embeddings

# # Email Settings (for Interview Scheduling Agent)
# # For development/testing: emails will be printed to console
# # For production: configure SMTP settings below

# # Check if EMAIL_BACKEND is set in environment, otherwise use console for development
# email_backend_env = os.getenv('EMAIL_BACKEND', '')

# # If SMTP backend is requested, check if all required settings are present
# if email_backend_env == 'django.core.mail.backends.smtp.EmailBackend' or 'smtp' in email_backend_env.lower():
#     # SMTP backend requested - check if all settings are configured
#     email_host = os.getenv('EMAIL_HOST', '')
#     email_user = os.getenv('EMAIL_HOST_USER', '')
#     email_password = os.getenv('EMAIL_HOST_PASSWORD', '')
    
#     if not email_host or not email_user or not email_password:
#         # SMTP settings incomplete - fallback to console backend
#         print("\n" + "="*60)
#         print("⚠️  WARNING: SMTP backend requested but settings incomplete!")
#         print("   Missing: EMAIL_HOST, EMAIL_HOST_USER, or EMAIL_HOST_PASSWORD")
#         print("   Falling back to console backend (emails will print to terminal)")
#         print("="*60 + "\n")
#         EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#     else:
#         # All SMTP settings present - use SMTP
#         EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#         EMAIL_HOST = email_host
#         EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
#         EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
#         EMAIL_HOST_USER = email_user
#         EMAIL_HOST_PASSWORD = email_password
# else:
#     # Default: Use console backend for development
#     EMAIL_BACKEND = email_backend_env or 'django.core.mail.backends.console.EmailBackend'

# DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# # Recruiter Email (fallback if user doesn't have email)
# RECRUITER_EMAIL = os.getenv('RECRUITER_EMAIL', '')
# GROQ_REC_API_KEY = os.getenv('GROQ_REC_API_KEY', '')


"""
Django settings for project_manager_ai project.
Generated by 'django-admin startproject' using Django 5.0.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9hce6%w7!*)lb#$^6)gb8!h01#6t6y_85nn=exz82l4dj=6q45'
DEBUG = True
ALLOWED_HOSTS = []


# --------------------
# Applications
# --------------------
def _startup_print(*args, **kwargs):
    """Print once when Django's autoreloader is enabled."""
    if os.environ.get('RUN_MAIN') == 'true':
        print(*args, **kwargs)

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-9hce6%w7!*)lb#$^6)gb8!h01#6t6y_85nn=exz82l4dj=6q45'
DEBUG = True
ALLOWED_HOSTS = []


# --------------------
# Applications
# --------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',  # CORS support for frontend

    'core',
    'project_manager_agent',
    'recruitment_agent',
    'marketing_agent.apps.MarketingAgentConfig',  # Use app config for agent registration
    'Frontline_agent.apps.FrontlineAgentConfig',  # Frontline Agent app
    'api',  # API app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be as high as possible)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'recruitment_agent.middleware.AutoInterviewFollowupMiddleware',  # Auto follow-up email checking
]

ROOT_URLCONF = 'project_manager_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_manager_ai.wsgi.application'


# --------------------
# Database
# --------------------

# Default to SQLite for local development unless explicitly overridden.
# Set `USE_SQL_SERVER=true` in your environment to enable SQL Server.
USE_SQL_SERVER = os.getenv('USE_SQL_SERVER', 'False').strip().lower() == 'true'

if USE_SQL_SERVER:
    USE_WINDOWS_AUTH = os.getenv('USE_WINDOWS_AUTH', 'True').strip().lower() == 'true'

    # For named instances, set DB_HOST like: localhost\\SQLEXPRESS
    # For a default instance, set DB_HOST=localhost and (optionally) DB_PORT=1433
    db_host = os.getenv('DB_HOST', r'localhost').strip()
    db_port = os.getenv('DB_PORT', '').strip()

    extra_params_parts: list[str] = []
    if USE_WINDOWS_AUTH:
        extra_params_parts.append('Trusted_Connection=yes')
    
    extra_params = ';'.join(extra_params_parts) if extra_params_parts else ''
    
    db_config = {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_NAME', 'project_manager_db'),
        'HOST': r'localhost',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'trusted_connection': 'yes',
        },
    }

    # Only set PORT if provided (named instances typically omit PORT)
    if db_port:
        db_config['PORT'] = db_port

    if not USE_WINDOWS_AUTH:
        db_config['USER'] = os.getenv('DB_USER', '').strip()
        db_config['PASSWORD'] = os.getenv('DB_PASSWORD', '').strip()

    DATABASES = {'default': db_config}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# --------------------
# Password validation
# --------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------
# Internationalization
# --------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------
# Static files
# --------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# --------------------
# Media files (for file uploads)
# --------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --------------------
# Default PK
# --------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------
# Auth redirects
# --------------------
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'


# --------------------
# AI / API Settings
# --------------------
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.1-8b-instant')
GROQ_REC_API_KEY = os.getenv('GROQ_REC_API_KEY', '')


# --------------------
# Email Configuration
# --------------------
# Check EMAIL_BACKEND from .env (remove quotes if present)
email_backend_env = os.getenv('EMAIL_BACKEND', '').strip().strip("'\"")
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').strip()

# Check if SMTP is requested (either full path or 'smtp' keyword)
if email_backend_env and ('smtp' in email_backend_env.lower() or 'EmailBackend' in email_backend_env):
    # SMTP Configuration for actual email sending
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com').strip()
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower().strip() == 'true'
    EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower().strip() == 'true'
    
    # Verify SMTP settings are configured
    if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
        _startup_print("\n" + "="*60)
        _startup_print("WARNING: SMTP backend requested but EMAIL_HOST_USER or EMAIL_HOST_PASSWORD not set!")
        _startup_print("Falling back to console backend (emails will print to terminal)")
        _startup_print("="*60 + "\n")
        EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    else:
        _startup_print("\n" + "="*60)
        _startup_print("EMAIL CONFIGURATION:")
        _startup_print(f"  Backend: SMTP")
        _startup_print(f"  Host: {EMAIL_HOST}")
        _startup_print(f"  Port: {EMAIL_PORT}")
        _startup_print(f"  From: {EMAIL_HOST_USER}")
        _startup_print("="*60 + "\n")
else:
    # Console backend (for development - emails print to terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    _startup_print("\n" + "="*60)
    _startup_print("INFO: Using console email backend (emails will print to terminal)")
    _startup_print("To send actual emails, set in .env:")
    _startup_print("  EMAIL_BACKEND=smtp")
    _startup_print("  EMAIL_HOST_USER=your-email@gmail.com")
    _startup_print("  EMAIL_HOST_PASSWORD=your-app-password")
    _startup_print("="*60 + "\n")

SITE_URL = os.getenv('SITE_URL', 'https://fiddly-uncouth-ryan.ngrok-free.dev')


# --------------------
# REST Framework Configuration
# --------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# --------------------
# CORS Settings (for frontend API access)
# --------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Vite dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Alternative Vite port
    "http://127.0.0.1:5173",
]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allow all headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-company-user-id',  # Custom header for company user authentication
    'x-company-id',  # Custom header for company authentication
]

# Allow all methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
