"""
Lead Research & Enrichment Agent
---------------------------------
Finds B2B sales leads matching the company's Ideal Customer Profile.

Sources (in priority order):
  1. Apollo.io REST API  — if APOLLO_API_KEY is set in .env / Django settings
  2. Groq AI generation  — realistic demo leads generated by LLM (always available)
"""

import json
import logging
import os

import requests
from django.conf import settings

logger = logging.getLogger(__name__)

APOLLO_SEARCH_URL = "https://api.apollo.io/v1/mixed_people/search"

# Apollo employee-range strings
APOLLO_SIZE_BUCKETS = [
    (1, 10, "1,10"),
    (11, 50, "11,50"),
    (51, 200, "51,200"),
    (201, 500, "201,500"),
    (501, 1000, "501,1000"),
    (1001, 5000, "1001,5000"),
    (5001, 10000, "5001,10000"),
]


class LeadResearchAgent:
    """Finds and enriches leads against an ICP profile."""

    def __init__(self):
        self.apollo_api_key = (
            getattr(settings, 'APOLLO_API_KEY', None)
            or os.environ.get('APOLLO_API_KEY', '')
        ).strip()

        groq_key = (
            getattr(settings, 'GROQ_API_KEY', None)
            or getattr(settings, 'GROQ_REC_API_KEY', None)
            or os.environ.get('GROQ_API_KEY', '')
            or os.environ.get('GROQ_REC_API_KEY', '')
        ).strip()

        self.groq_client = None
        if groq_key:
            try:
                from groq import Groq
                self.groq_client = Groq(api_key=groq_key)
            except Exception as exc:
                logger.error("Groq init failed in LeadResearchAgent: %s", exc)

        self.model = getattr(settings, 'GROQ_MODEL', 'llama-3.1-8b-instant')

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def search_leads(self, icp_profile, count: int = 20) -> list[dict]:
        """Return a list of raw lead dicts for the given ICP profile."""
        if self.apollo_api_key:
            return self._search_apollo(icp_profile, count)
        return self._generate_ai_leads(icp_profile, count)

    @property
    def source_label(self) -> str:
        return 'apollo' if self.apollo_api_key else 'ai_generated'

    # ------------------------------------------------------------------
    # Apollo.io
    # ------------------------------------------------------------------

    def _search_apollo(self, icp, count: int) -> list[dict]:
        payload = {
            "api_key": self.apollo_api_key,
            "page": 1,
            "per_page": min(count, 25),
        }

        if icp.job_titles:
            payload["q_titles"] = icp.job_titles[:10]

        if icp.locations:
            payload["person_locations"] = icp.locations[:5]

        size_min = icp.company_size_min or 0
        size_max = icp.company_size_max or 999_999
        if icp.company_size_min or icp.company_size_max:
            payload["organization_num_employees_ranges"] = [
                label for lo, hi, label in APOLLO_SIZE_BUCKETS
                if lo <= size_max and hi >= size_min
            ] or ["11,50", "51,200"]

        if icp.keywords:
            payload["q_keywords"] = " ".join(icp.keywords[:5])

        try:
            resp = requests.post(
                APOLLO_SEARCH_URL,
                json=payload,
                headers={"Content-Type": "application/json", "Cache-Control": "no-cache"},
                timeout=30,
            )
            resp.raise_for_status()
            people = resp.json().get('people', [])
            return [self._parse_apollo_person(p) for p in people]
        except requests.RequestException as exc:
            logger.error("Apollo API error: %s", exc)
            raise ValueError(f"Apollo.io request failed: {exc}") from exc

    def _parse_apollo_person(self, person: dict) -> dict:
        org = person.get('organization') or {}
        full_name = person.get('name', '')
        parts = full_name.split(' ', 1)
        return {
            'apollo_id': person.get('id', ''),
            'first_name': parts[0] if parts else '',
            'last_name': parts[1] if len(parts) > 1 else '',
            'full_name': full_name,
            'email': person.get('email', ''),
            'phone': person.get('phone', ''),
            'job_title': person.get('title', ''),
            'seniority_level': person.get('seniority', ''),
            'department': (person.get('departments') or [''])[0],
            'company_name': org.get('name', ''),
            'company_domain': org.get('primary_domain', ''),
            'company_industry': org.get('industry', ''),
            'company_size': org.get('estimated_num_employees') or None,
            'company_size_range': '',
            'company_location': person.get('city', ''),
            'company_technologies': (org.get('current_technologies') or [])[:10],
            'linkedin_url': person.get('linkedin_url', ''),
            'company_linkedin_url': org.get('linkedin_url', ''),
            'company_website': org.get('website_url', ''),
            'recent_news': [],
            'buying_signals': [],
            'source': 'apollo',
            'raw_data': person,
        }

    # ------------------------------------------------------------------
    # Groq AI lead generation (fallback / demo)
    # ------------------------------------------------------------------

    def _generate_ai_leads(self, icp, count: int) -> list[dict]:
        if not self.groq_client:
            raise ValueError(
                "No lead source available. Configure APOLLO_API_KEY or GROQ_API_KEY."
            )

        industries = ", ".join(icp.industries) if icp.industries else "Technology, SaaS"
        titles = ", ".join(icp.job_titles) if icp.job_titles else "CEO, VP Sales, Head of Marketing"
        locations = ", ".join(icp.locations) if icp.locations else "United States"
        size = (
            f"{icp.company_size_min or 10}-{icp.company_size_max or 500}"
            if (icp.company_size_min or icp.company_size_max)
            else "10-500"
        )
        keywords = ", ".join(icp.keywords) if icp.keywords else ""

        system_prompt = (
            "You are a B2B sales data expert. "
            "Return ONLY a valid JSON array, no markdown, no extra text."
        )

        # Generate in batches of 5 to stay within Groq free-tier TPM limits
        BATCH_SIZE = 5
        all_leads = []
        batches = (count + BATCH_SIZE - 1) // BATCH_SIZE

        for batch_i in range(batches):
            batch_count = min(BATCH_SIZE, count - len(all_leads))
            if batch_count <= 0:
                break

            user_prompt = f"""Generate {batch_count} B2B sales leads matching this ICP:
Industries: {industries} | Titles: {titles} | Size: {size} employees | Locations: {locations}{" | Tech: " + keywords if keywords else ""}

Return a JSON array with {batch_count} objects, each having these keys:
first_name, last_name, full_name, email, phone, job_title, seniority_level, department,
company_name, company_domain, company_industry, company_size (integer), company_size_range,
company_location, linkedin_url, company_linkedin_url, company_website,
company_technologies (array of 2-3 strings),
recent_news (array with 1 object: title, date, summary),
buying_signals (array of 2 short strings), source ("ai_generated")

Use realistic varied data matching the ICP."""

            try:
                resp = self.groq_client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=0.75,
                    max_tokens=3000,
                )

                content = resp.choices[0].message.content.strip()

                # Strip markdown fences if present
                if "```" in content:
                    parts = content.split("```")
                    for part in parts:
                        if "[" in part or "{" in part:
                            content = part.lstrip("json").strip()
                            break

                batch_leads = json.loads(content)
                if not isinstance(batch_leads, list):
                    batch_leads = [batch_leads]

                for lead in batch_leads:
                    lead.setdefault('apollo_id', '')
                    lead.setdefault('raw_data', {})
                    lead['source'] = 'ai_generated'

                all_leads.extend(batch_leads)
                logger.info("Batch %d/%d: got %d leads", batch_i + 1, batches, len(batch_leads))

            except json.JSONDecodeError as exc:
                logger.error("Groq returned invalid JSON in batch %d: %s", batch_i + 1, exc)
                if not all_leads:
                    raise ValueError("AI returned invalid JSON — please try again.") from exc
                break
            except Exception as exc:
                logger.error("AI lead generation failed in batch %d: %s", batch_i + 1, exc)
                if not all_leads:
                    raise
                break

        if not all_leads:
            raise ValueError("No leads generated — please try again.")

        return all_leads
