// Tasks panel for the AI Executive Meeting Assistant — extracted from
// ExecMeetingDashboard.jsx. Pure presentation: all state and handlers are
// passed in as props; the panel never owns state itself.

import React from 'react';
import { Button } from '@/components/ui/button';
import {
  Loader2, ListChecks, Sparkles, Plus, Download, Trash2, Pencil, RefreshCw, ChevronRight,
} from 'lucide-react';
import {
  CARD_STYLE, ROW_STYLE, priorityBadge, statusBadge, AssigneeAvatars, EmptyState,
  BulkSelectBar, SelectCheckbox,
} from '../shared';

export const TasksPanel = ({
  tasks, tasksLoading, prioritizeLoading, prioritizeResult,
  expandedTaskId, expandedSubtasksId,
  loadTasks, runAiPrioritize, setShowTaskDialog, setPrioritizeResult,
  setExpandedTaskId, setExpandedSubtasksId, setEditingTask,
  setSubtaskParentTask, setConfirmDeleteTaskId, toast,
  selectedTaskIds, toggleSelected, setSelectedTaskIds, bulkDeleteTasks, bulkDeleting,
}) => (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-white font-semibold flex items-center gap-2">
          <ListChecks className="h-4 w-4 text-sky-400" />
          Tasks
        </h3>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="ghost" onClick={loadTasks} disabled={tasksLoading} className="text-white/40 hover:text-white">
            <RefreshCw className={`h-3.5 w-3.5 ${tasksLoading ? 'animate-spin' : ''}`} />
          </Button>
          <Button size="sm" variant="outline"
            onClick={runAiPrioritize} disabled={prioritizeLoading || tasks.length === 0}
            className="border-violet-500/40 text-violet-300 hover:bg-violet-500/10 text-xs gap-1.5">
            {prioritizeLoading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
            AI Prioritize
          </Button>
          <Button size="sm" onClick={() => setShowTaskDialog(true)} style={{ background: 'linear-gradient(90deg, #a259ff 0%, #7c3aed 100%)' }} className="text-white border-0 hover:opacity-90">
            <Plus className="h-4 w-4 mr-1" /> Add Task
          </Button>
        </div>
      </div>

      {/* AI prioritization result */}
      {Array.isArray(prioritizeResult) && prioritizeResult.length > 0 && (
        <div className="rounded-2xl p-4 space-y-2" style={CARD_STYLE}>
          <div className="flex items-center justify-between mb-1">
            <p className="text-violet-300 text-xs font-semibold flex items-center gap-1.5">
              <Sparkles className="h-3.5 w-3.5" /> AI Prioritization Result
            </p>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="ghost" className="text-white/40 hover:text-white h-6 px-2 text-xs gap-1"
                onClick={async () => {
                  try {
                    const { default: jsPDF } = await import('jspdf');
                    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
                    const pageW = pdf.internal.pageSize.getWidth();
                    const pageH = pdf.internal.pageSize.getHeight();
                    const margin = 18;
                    const contentW = pageW - margin * 2;

                    pdf.setFillColor(109, 40, 217);
                    pdf.rect(0, 0, pageW, 12, 'F');

                    pdf.setFont('helvetica', 'bold');
                    pdf.setFontSize(18);
                    pdf.setTextColor(30, 10, 60);
                    pdf.text('AI Task Prioritization', margin, 24);
                    let y = 32;

                    pdf.setFont('helvetica', 'normal');
                    pdf.setFontSize(8.5);
                    pdf.setTextColor(120, 100, 160);
                    pdf.text(`Generated by AI Executive Meeting Assistant · ${new Date().toLocaleDateString()}`, margin, y);
                    y += 5;
                    pdf.setDrawColor(109, 40, 217); pdf.setLineWidth(0.4);
                    pdf.line(margin, y, pageW - margin, y); y += 7;

                    prioritizeResult.forEach((t, i) => {
                      if (y > pageH - 25) { pdf.addPage(); y = 18; }
                      const priorityColors = { critical: [185,28,28], high: [194,65,12], medium: [161,98,7], low: [21,128,61] };
                      const [r,g,b] = priorityColors[t.priority] || [109,40,217];
                      pdf.setFillColor(r, g, b);
                      pdf.roundedRect(margin, y - 3, 18, 5.5, 1, 1, 'F');
                      pdf.setFont('helvetica', 'bold'); pdf.setFontSize(7); pdf.setTextColor(255,255,255);
                      pdf.text((t.priority || 'medium').toUpperCase(), margin + 1.5, y + 1);

                      pdf.setFont('helvetica', 'bold'); pdf.setFontSize(11); pdf.setTextColor(30,10,60);
                      const titleW = pdf.splitTextToSize(`${i+1}. ${t.title || 'Untitled Task'}`, contentW - 22);
                      pdf.text(titleW, margin + 21, y + 1);
                      y += titleW.length * 6 + 2;

                      if (t.ai_reasoning) {
                        pdf.setFont('helvetica', 'normal'); pdf.setFontSize(9.5); pdf.setTextColor(80,60,120);
                        const rLines = pdf.splitTextToSize(t.ai_reasoning, contentW - 4);
                        rLines.forEach(l => { if (y > pageH-20){pdf.addPage();y=18;} pdf.text(l, margin+2, y); y+=5; });
                      }
                      if (t.suggested_due_date) {
                        pdf.setFont('helvetica', 'italic'); pdf.setFontSize(8.5); pdf.setTextColor(109,40,217);
                        pdf.text(`Suggested deadline: ${t.suggested_due_date}`, margin+2, y); y+=5;
                      }
                      pdf.setDrawColor(220,210,240); pdf.setLineWidth(0.2);
                      pdf.line(margin, y, pageW-margin, y); y+=5;
                    });

                    const totalPages = pdf.internal.getNumberOfPages();
                    for (let i=1; i<=totalPages; i++) {
                      pdf.setPage(i); pdf.setFontSize(7.5); pdf.setTextColor(160,140,190);
                      pdf.text(`Page ${i} of ${totalPages}  ·  AI Executive Meeting Assistant`, margin, pageH-7);
                    }
                    pdf.save(`task-prioritization-${new Date().toISOString().slice(0,10)}.pdf`);
                  } catch(err) {
                    toast({ title: 'PDF download failed', description: err?.message, variant: 'destructive' });
                  }
                }}>
                <Download className="h-3 w-3" /> PDF
              </Button>
              <button onClick={() => setPrioritizeResult(null)} className="text-white/30 hover:text-white text-xs">✕ Close</button>
            </div>
          </div>
          {prioritizeResult.map((t, i) => (
            <div key={t.id || i} className="rounded-xl p-3 bg-white/5 border border-white/10 space-y-0.5">
              <div className="flex items-center gap-2">
                {priorityBadge(t.priority)}
                <p className="text-white text-xs font-medium truncate">{i+1}. {t.title || 'Untitled Task'}</p>
              </div>
              {t.ai_reasoning && <p className="text-white/50 text-xs">{t.ai_reasoning}</p>}
              {t.suggested_due_date && <p className="text-violet-300/60 text-xs">Suggested deadline: {t.suggested_due_date}</p>}
            </div>
          ))}
        </div>
      )}

      {tasksLoading ? (
        <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-violet-400" /></div>
      ) : !Array.isArray(tasks) || tasks.length === 0 ? (
        <EmptyState icon={ListChecks} label="No tasks yet" />
      ) : (
        <>
        <BulkSelectBar
          allIds={tasks.map(t => t.id)}
          selected={selectedTaskIds}
          onToggleAll={() => setSelectedTaskIds(selectedTaskIds.size === tasks.length ? new Set() : new Set(tasks.map(t => t.id)))}
          onDelete={bulkDeleteTasks}
          deleting={bulkDeleting}
          label="task"
        />
        <div className="rounded-2xl overflow-hidden" style={CARD_STYLE}>
          {tasks.map(t => {
            const isOpen = expandedTaskId === t.id;
            const subtasks = t.subtasks || [];
            const subtaskDone = t.subtask_done_count || 0;
            const subtaskTotal = t.subtask_count ?? subtasks.length;
            // Weighted progress so the bar also moves for in-progress work, not
            // just fully-done subtasks: done = 1.0, in_progress/review = 0.5.
            const subtaskProgress = subtaskTotal > 0
              ? Math.round(
                  (subtasks.reduce((sum, st) => sum + (st.status === 'done' ? 1 : (st.status === 'in_progress' || st.status === 'review') ? 0.5 : 0), 0) / subtaskTotal) * 100
                )
              : 0;
            return (
              <div key={t.id} style={ROW_STYLE}>
                {/* ── Row ── */}
                <div
                  className="flex items-center gap-4 px-4 py-3 cursor-pointer hover:bg-white/[0.04] transition-colors"
                  onClick={() => setExpandedTaskId(isOpen ? null : t.id)}
                >
                  <SelectCheckbox
                    checked={selectedTaskIds.has(t.id)}
                    onChange={() => toggleSelected(setSelectedTaskIds, t.id)}
                  />
                  <div className="flex-1 min-w-0">
                    <p className="text-white text-sm font-medium truncate">{t.title}</p>
                    <div className="flex items-center gap-1.5 mt-0.5">
                      <p className="text-white/40 text-xs">
                        {t.due_date ? `Due: ${t.due_date}` : 'No due date'}
                      </p>
                      {subtaskTotal > 0 && (
                        <span className="text-white/30 text-xs flex items-center gap-1">
                          · <ListChecks className="h-3 w-3" />{subtaskDone}/{subtaskTotal}
                        </span>
                      )}
                      <AssigneeAvatars assignees={t.assignees} />
                    </div>
                  </div>
                  <div className="flex items-center gap-2 flex-shrink-0">
                    {priorityBadge(t.priority)}
                    {statusBadge(t.status)}
                    {/* Quick actions inline with the badges */}
                    <div className="flex items-center gap-0.5">
                      <button
                        type="button" title="Edit"
                        onClick={e => { e.stopPropagation(); setEditingTask(t); }}
                        className="p-1 rounded text-white/30 hover:text-violet-300 hover:bg-violet-500/10 transition-colors">
                        <Pencil className="h-3.5 w-3.5" />
                      </button>
                      <button
                        type="button" title="Add subtask"
                        onClick={e => { e.stopPropagation(); setSubtaskParentTask(t); }}
                        className="p-1 rounded text-white/30 hover:text-sky-300 hover:bg-sky-500/10 transition-colors">
                        <Plus className="h-3.5 w-3.5" />
                      </button>
                      <button
                        type="button" title="Delete"
                        onClick={e => { e.stopPropagation(); setConfirmDeleteTaskId(t.id); }}
                        className="p-1 rounded text-white/30 hover:text-red-400 hover:bg-red-500/10 transition-colors">
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                    <ChevronRight className={`h-4 w-4 text-white/30 transition-transform ${isOpen ? 'rotate-90' : ''}`} />
                  </div>
                </div>

                {/* ── Inline detail panel ── */}
                {isOpen && (
                  <div className="px-4 pb-4 pt-2 border-t border-white/5 space-y-3">
                    {t.description && (
                      <p className="text-white/60 text-xs whitespace-pre-wrap">{t.description}</p>
                    )}
                    {(t.assignees || []).length > 0 && (
                      <div className="flex flex-wrap gap-1.5">
                        {t.assignees.map(a => (
                          <span key={a.id} className="inline-flex items-center gap-1.5 pl-1 pr-2.5 py-0.5 rounded-full bg-violet-500/20 border border-violet-500/30 text-violet-200 text-xs">
                            <span className="h-4 w-4 rounded-full bg-violet-500/40 flex items-center justify-center text-[9px] font-semibold">
                              {a.full_name?.[0]?.toUpperCase() || '?'}
                            </span>
                            {a.full_name}
                          </span>
                        ))}
                      </div>
                    )}
                    {t.ai_reasoning && (
                      <p className="text-white/40 text-xs italic">{t.ai_reasoning}</p>
                    )}

                    {/* Subtasks accordion */}
                    {subtasks.length > 0 && (() => {
                      const subOpen = expandedSubtasksId === t.id;
                      const pct = subtaskProgress;
                      return (
                        <div className="rounded-lg border border-white/10 bg-white/[0.02] overflow-hidden">
                          {/* Accordion header */}
                          <button
                            type="button"
                            className="w-full flex items-center gap-3 px-3 py-2 hover:bg-white/[0.04] transition-colors"
                            onClick={e => { e.stopPropagation(); setExpandedSubtasksId(subOpen ? null : t.id); }}
                          >
                            <ChevronRight className={`h-3.5 w-3.5 text-white/40 transition-transform ${subOpen ? 'rotate-90' : ''}`} />
                            <ListChecks className="h-3.5 w-3.5 text-sky-400" />
                            <span className="text-xs font-medium text-white/80">Subtasks</span>
                            <span className="text-[10px] text-white/40">{subtaskDone}/{subtaskTotal}</span>
                            {/* progress bar */}
                            <div className="flex-1 h-1 rounded-full bg-white/10 overflow-hidden">
                              <div className="h-full bg-sky-400/70 transition-all" style={{ width: `${pct}%` }} />
                            </div>
                          </button>

                          {/* Accordion body */}
                          {subOpen && (
                            <div className="px-2 pb-2 space-y-1.5">
                              {subtasks.map(st => (
                                <div key={st.id}
                                  className="flex items-center gap-3 rounded-lg px-3 py-2 bg-white/[0.03] border border-white/5 cursor-pointer hover:bg-white/[0.06]"
                                  onClick={e => { e.stopPropagation(); setEditingTask(st); }}>
                                  <div className="flex-1 min-w-0">
                                    <p className={`text-xs font-medium truncate ${st.status === 'done' ? 'text-white/40 line-through' : 'text-white/80'}`}>{st.title}</p>
                                    {st.due_date && <p className="text-white/30 text-[10px]">Due: {st.due_date}</p>}
                                  </div>
                                  <AssigneeAvatars assignees={st.assignees} size="sm" />
                                  {priorityBadge(st.priority)}
                                  {statusBadge(st.status)}
                                  <button
                                    className="text-white/20 hover:text-red-400 text-xs px-1"
                                    onClick={e => { e.stopPropagation(); setConfirmDeleteTaskId(st.id); }}>
                                    <Trash2 className="h-3 w-3" />
                                  </button>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>
                      );
                    })()}
                  </div>
                )}
              </div>
            );
          })}
        </div>
        </>
      )}
    </div>
);
