# Generated by Django 5.0.1 on 2026-05-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20260516_0125'),
        ('crm_sync_agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crmcontactmapping',
            name='unique_integration_source',
        ),
        migrations.RemoveConstraint(
            model_name='crmintegration',
            name='unique_company_provider',
        ),
        migrations.RenameIndex(
            model_name='crmcontactmapping',
            new_name='crm_contact_integra_a28579_idx',
            old_name='crm_contact_map_idx',
        ),
        migrations.RenameIndex(
            model_name='crmsynclog',
            new_name='crm_sync_lo_company_0d36ae_idx',
            old_name='crm_log_company_time_idx',
        ),
        migrations.RenameIndex(
            model_name='crmsynclog',
            new_name='crm_sync_lo_integra_cffdb4_idx',
            old_name='crm_log_integration_status_idx',
        ),
        migrations.RenameIndex(
            model_name='crmsyncqueue',
            new_name='crm_sync_qu_status_7eb489_idx',
            old_name='crm_queue_status_pri_time_idx',
        ),
        migrations.RenameIndex(
            model_name='crmsyncqueue',
            new_name='crm_sync_qu_company_b7e97b_idx',
            old_name='crm_queue_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='crmsyncqueue',
            new_name='crm_sync_qu_integra_48d9a0_idx',
            old_name='crm_queue_integration_status_idx',
        ),
        migrations.AlterUniqueTogether(
            name='crmcontactmapping',
            unique_together={('integration', 'source_type', 'source_id')},
        ),
        migrations.AlterUniqueTogether(
            name='crmintegration',
            unique_together={('company', 'provider')},
        ),
    ]
