# Generated by Django 4.2.10 on 2026-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_sync_agent', '0002_remove_crmcontactmapping_unique_integration_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmintegration',
            name='limit_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crmintegration',
            name='limit_reached',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crmintegration',
            name='limit_reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
