# Generated by Django 5.0.1 on 2026-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsdocument',
            name='file',
            field=models.FileField(max_length=1000, upload_to='operations/documents/%Y/%m/'),
        ),
    ]
