# Generated by Django 5.0.1 on 2026-04-01 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_operations_agent_choices'),
        ('operations_agent', '0003_add_summary_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsDocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_type', models.CharField(default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('rich_summary', models.TextField(help_text='Full markdown summary')),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_summaries', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_summaries', to='core.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
