# Generated by Django 5.0.1 on 2026-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0004_add_document_summary_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='deadlines',
            field=models.JSONField(blank=True, default=list, help_text='Key dates/deadlines found'),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='document_category',
            field=models.CharField(blank=True, help_text='Auto-classified category', max_length=50),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='people, organizations, dates, amounts, locations'),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='importance_level',
            field=models.CharField(blank=True, help_text='critical/high/medium/low', max_length=20),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='importance_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='opportunities',
            field=models.JSONField(blank=True, default=list, help_text='Identified opportunities'),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='risks',
            field=models.JSONField(blank=True, default=list, help_text='Identified risks/concerns'),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='sentiment',
            field=models.CharField(blank=True, help_text='positive/negative/neutral/mixed', max_length=30),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='sentiment_explanation',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='topics',
            field=models.JSONField(blank=True, default=list, help_text='Main topics/categories'),
        ),
    ]
