# Generated by Django 5.0.1 on 2026-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0005_operationsdocumentsummary_deadlines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsgenerateddocument',
            name='tokens_used',
            field=models.JSONField(blank=True, default=dict, help_text='Groq usage for the latest generation: prompt/completion/total tokens.'),
        ),
    ]
