# Generated by Django 4.2.10 on 2026-07-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0006_operationsgenerateddocument_tokens_used'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='operationsdocument',
            index=models.Index(fields=['company', 'is_processed', '-created_at'], name='ops_doc_company_proc_created'),
        ),
    ]
