# Generated by Django 4.2.10 on 2026-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0007_operationsdocument_ops_doc_company_proc_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocument',
            name='chunks_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='chunks_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationsdocument',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='operationsdocumentchunk',
            name='section_heading',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddIndex(
            model_name='operationsdocument',
            index=models.Index(fields=['processing_status'], name='ops_doc_proc_status'),
        ),
    ]
