# Generated by Django 4.2.10 on 2026-07-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0008_operationsdocument_chunks_processed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operationsdocumentchunk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='operationsdocumentchunk',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='operations_agent.operationsdocumentsummary'),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='parsed_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='operationsdocumentchunk',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='operations_agent.operationsdocument'),
        ),
        migrations.AddIndex(
            model_name='operationsdocumentchunk',
            index=models.Index(fields=['summary', 'chunk_index'], name='ops_chunk_summary_idx'),
        ),
    ]
