# Generated by Django 4.2.10 on 2026-07-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0009_alter_operationsdocumentchunk_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='operationsdocumentsummary',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', max_length=20),
        ),
    ]
