# Generated by Django 4.2.10 on 2026-07-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_agent', '0010_operationsdocumentsummary_processing_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='operationsdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash__gt', '')), fields=('company', 'file_hash'), name='uq_ops_doc_company_filehash'),
        ),
    ]
