# Generated by Django 5.2.9 on 2026-01-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0002_alter_document_uploaded_by_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='Frontline_a_documen_a909fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='Frontline_a_created_fd85d4_idx',
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
