# Generated by Django 4.2.7 on 2026-02-05 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_frontline_agent_module'),
        ('Frontline_agent', '0002_alter_document_uploaded_by_alter_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company that owns this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_documents', to='core.company'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_content',
            field=models.TextField(blank=True, help_text='Extracted text content from document'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('doc', 'DOC'), ('txt', 'TXT'), ('md', 'Markdown'), ('html', 'HTML'), ('other', 'Other')], default='other', help_text='File format/extension', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash for duplicate detection', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='is_indexed',
            field=models.BooleanField(default=False, help_text='Whether document content is indexed for search'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ticket_attachment', 'Ticket Attachment'), ('knowledge_base', 'Knowledge Base'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('report', 'Report'), ('other', 'Other')], default='knowledge_base', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'is_indexed'], name='Frontline_a_company_276216_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='Frontline_a_file_ha_e2ecbb_idx'),
        ),
    ]
