# Generated by Django 4.2.7 on 2026-02-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0003_document_company_document_document_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector embedding for semantic search (stored as list)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Model used to generate embedding (e.g., text-embedding-3-large)', max_length=100),
        ),
    ]
