# Generated by Django 4.2.7 on 2026-02-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0004_add_embedding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Model used to generate embedding (e.g., text-embedding-3-large)', max_length=100, null=True),
        ),
    ]
