# Generated by Django 4.2.7 on 2026-02-10 21:08

from django.db import migrations, models
import json


def convert_embeddings_to_json_string(apps, schema_editor):
    """Convert existing JSONField embeddings to JSON strings for TextField"""
    Document = apps.get_model('Frontline_agent', 'Document')
    for doc in Document.objects.exclude(embedding__isnull=True).exclude(embedding=''):
        if doc.embedding:
            # If it's already a string, keep it; if it's a list/dict, convert to JSON string
            if not isinstance(doc.embedding, str):
                doc.embedding = json.dumps(doc.embedding)
                doc.save(update_fields=['embedding'])


def reverse_convert_embeddings(apps, schema_editor):
    """Reverse: Convert JSON strings back to Python objects (for rollback)"""
    Document = apps.get_model('Frontline_agent', 'Document')
    for doc in Document.objects.exclude(embedding__isnull=True).exclude(embedding=''):
        if doc.embedding and isinstance(doc.embedding, str):
            try:
                doc.embedding = json.loads(doc.embedding)
                doc.save(update_fields=['embedding'])
            except json.JSONDecodeError:
                # If it's not valid JSON, leave it as is
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0005_fix_embedding_model_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=models.TextField(blank=True, help_text='Vector embedding for semantic search (stored as JSON string to support large embeddings)', null=True),
        ),
        migrations.RunPython(convert_embeddings_to_json_string, reverse_convert_embeddings),
    ]
