# Generated by Django 4.2+ for Frontline QA Chats

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_frontline_agent_module'),
        ('Frontline_agent', '0007_alter_embedding_to_nvarchar_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontlineQAChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', help_text='Chat title (e.g. first question snippet)', max_length=255)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(help_text='Company user who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='frontline_qa_chats', to='core.companyuser')),
            ],
            options={
                'verbose_name': 'Frontline QA Chat',
                'verbose_name_plural': 'Frontline QA Chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FrontlineQAChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('response_data', models.JSONField(blank=True, help_text='For assistant: full API response { answer, has_verified_info, source, type }', null=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Frontline_agent.frontlineqachat')),
            ],
            options={
                'verbose_name': 'Frontline QA Chat Message',
                'verbose_name_plural': 'Frontline QA Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
