# Generated by Django 4.2.7 on 2026-02-16 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_add_frontline_agent_module'),
        ('Frontline_agent', '0008_frontlineqachat_frontlineqachatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, help_text='Email subject', max_length=300)),
                ('body', models.TextField(help_text='Body text. Use {{ticket_id}}, {{ticket_title}}, {{customer_name}}, {{resolution}} for placeholders.')),
                ('notification_type', models.CharField(choices=[('ticket_update', 'Ticket Update'), ('ticket_assigned', 'Ticket Assigned'), ('follow_up', 'Follow-up'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('system', 'System')], default='ticket_update', max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_notification_templates', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('billing', 'Billing'), ('account', 'Account'), ('feature_request', 'Feature Request'), ('bug', 'Bug'), ('knowledge_gap', 'Knowledge gap (add to KB)'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='FrontlineWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_conditions', models.JSONField(blank=True, default=dict, help_text='e.g. {"on": "ticket_created", "category": "billing"}')),
                ('steps', models.JSONField(default=list, help_text='List of steps: [{"type": "send_email", "template_id": 1}, {"type": "update_ticket", "status": "open"}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_workflows', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='frontlineworkflowexecution',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='Frontline_agent.frontlineworkflow'),
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Placeholder values for template')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_scheduled_notifications', to='core.company')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_scheduled_notifications_received', to=settings.AUTH_USER_MODEL)),
                ('related_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='Frontline_agent.ticket')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='Frontline_agent.notificationtemplate')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='Frontline_a_status_df17e3_idx'), models.Index(fields=['company'], name='Frontline_a_company_c063a8_idx')],
            },
        ),
    ]
