# Generated by Django 4.2+ for Frontline notification triggers

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0009_add_notification_workflow_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Optional: {"on": "ticket_created"|"ticket_updated", "delay_minutes": 0}. When set, notifications are auto-created on that event.'),
        ),
    ]
