# Generated migration for LLM-personalized notifications

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0010_notificationtemplate_trigger_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='use_llm_personalization',
            field=models.BooleanField(default=False, help_text='When enabled, the email body is generated by LLM from context (ticket, customer) for a personalized message; fallback to template body on failure.'),
        ),
    ]
