# Generated by Django 4.2.7 on 2026-03-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0015_frontlinenotificationpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='Sequential index of this chunk within the document')),
                ('chunk_text', models.TextField(help_text='Text content of this specific chunk')),
                ('embedding', models.TextField(blank=True, help_text='Vector embedding for this chunk (JSON string)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.RenameIndex(
            model_name='kbfeedback',
            new_name='Frontline_a_company_53371a_idx',
            old_name='Frontline_kb_company_idx',
        ),
        migrations.RenameIndex(
            model_name='kbfeedback',
            new_name='Frontline_a_documen_46d54f_idx',
            old_name='Frontline_kb_document_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='Frontline_a_sla_due_53d761_idx',
            old_name='Frontline_ticket_sla_due_idx',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document',
            field=models.ForeignKey(help_text='Parent document this chunk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='Frontline_agent.document'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='Frontline_a_documen_89bbac_idx'),
        ),
    ]
