# Generated by Django 4.2.7 on 2026-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0016_documentchunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontlineworkflow',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If True, execution halts until approved by admin'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted entities like user_id, product, etc.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='intent',
            field=models.CharField(blank=True, help_text='Extracted intention of the user', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frontlineworkflowexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('awaiting_approval', 'Awaiting Approval'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
