# Generated by Django 4.2.10 on 2026-04-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0018_llmusage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='llmusage',
            new_name='Frontline_a_company_2538e5_idx',
            old_name='fl_llm_usage_co_ct_idx',
        ),
        migrations.RenameIndex(
            model_name='llmusage',
            new_name='Frontline_a_company_c95c84_idx',
            old_name='fl_llm_usage_co_ag_ct_idx',
        ),
    ]
