from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0023_meeting_lifecycle'),
        ('core', '0041_company_frontline_widget_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from customer)'), ('outbound', 'Outbound (from agent / system)')], max_length=10)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('widget', 'Web widget'), ('api', 'API'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual entry')], default='email', max_length=20)),
                ('from_address', models.CharField(blank=True, help_text='Email address / handle of sender.', max_length=320)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_addresses', models.JSONField(blank=True, default=list, help_text='List of recipient addresses.')),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('body_text', models.TextField(blank=True, help_text='Plain-text body (reply-stripped when possible).')),
                ('body_html', models.TextField(blank=True, help_text='Sanitized HTML body (bleach-stripped).')),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='RFC 5322 Message-ID header. Used for reply threading.', max_length=998)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, help_text='In-Reply-To header from the incoming email.', max_length=998)),
                ('references', models.JSONField(blank=True, default=list, help_text='Ordered list of Message-IDs from the References header.')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Provider-normalized payload for debugging / re-processing.')),
                ('is_auto_reply', models.BooleanField(default=False, help_text='True if this was generated by an auto-response (e.g. bounce, vacation).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Frontline_agent.ticket')),
                ('author_user', models.ForeignKey(blank=True, help_text='Django user that sent this message (outbound).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_ticket_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('author_company_user', models.ForeignKey(blank=True, help_text='Company user that sent this message (outbound).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_ticket_messages_sent', to='core.companyuser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='fl_tmsg_tk_ctd_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['direction', 'channel'], name='fl_tmsg_dir_ch_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['message_id'], name='fl_tmsg_mid_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['in_reply_to'], name='fl_tmsg_irt_idx'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.IntegerField(default=0)),
                ('storage_path', models.CharField(help_text='Path on disk under MEDIA_ROOT.', max_length=1000)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Frontline_agent.ticketmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticketattachment',
            index=models.Index(fields=['ticket_message', 'created_at'], name='fl_tatt_tmsg_ctd_idx'),
        ),
    ]
