# Generated by Django 4.2.10 on 2026-04-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0019_rename_fl_llm_usage_co_ct_idx_frontline_a_company_2538e5_idx_and_more'),
        ('Frontline_agent', '0026_ticket_handoff_fields'),
    ]

    operations = [
    ]
