# Generated by Django 5.0.1 on 2026-04-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0027_merge_20260424_1601'),
        ('Frontline_agent', '0027_workflow_execution_pause'),
    ]

    operations = [
    ]
