# Generated by Django 4.2.10 on 2026-05-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0027_merge_20260424_1601'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contact',
            new_name='Frontline_a_company_f5fd63_idx',
            old_name='fl_contact_co_last_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='Frontline_a_company_de4957_idx',
            old_name='fl_contact_co_em_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='Frontline_a_externa_8aa620_idx',
            old_name='fl_contact_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='Frontline_a_process_759cae_idx',
            old_name='fl_doc_proc_status_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='Frontline_a_superse_8afa83_idx',
            old_name='fl_doc_superseded_idx',
        ),
        migrations.RenameIndex(
            model_name='frontlinemeeting',
            new_name='Frontline_a_company_21adab_idx',
            old_name='fl_mt_co_sched_idx',
        ),
        migrations.RenameIndex(
            model_name='frontlinemeeting',
            new_name='Frontline_a_schedul_f743b9_idx',
            old_name='fl_mt_sched_r24_idx',
        ),
        migrations.RenameIndex(
            model_name='frontlinemeeting',
            new_name='Frontline_a_schedul_8cd179_idx',
            old_name='fl_mt_sched_r15_idx',
        ),
        migrations.RenameIndex(
            model_name='frontlineworkflowversion',
            new_name='Frontline_a_workflo_21cf75_idx',
            old_name='fl_wf_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulednotification',
            new_name='Frontline_a_status_2d994a_idx',
            old_name='fl_sn_status_retry_idx',
        ),
        migrations.RenameIndex(
            model_name='schedulednotification',
            new_name='Frontline_a_dead_le_2ab18a_idx',
            old_name='fl_sn_dlq_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='Frontline_a_snoozed_35a3ae_idx',
            old_name='fl_ticket_snooze_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='Frontline_a_contact_e89821_idx',
            old_name='fl_ticket_contact_ct_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='Frontline_a_handoff_b82a2e_idx',
            old_name='fl_ticket_handoff_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketattachment',
            new_name='Frontline_a_ticket__1f0578_idx',
            old_name='fl_tatt_tmsg_ctd_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='Frontline_a_ticket__2f80f6_idx',
            old_name='fl_tmsg_tk_ctd_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='Frontline_a_directi_b6fbeb_idx',
            old_name='fl_tmsg_dir_ch_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='Frontline_a_message_9fc9b7_idx',
            old_name='fl_tmsg_mid_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketmessage',
            new_name='Frontline_a_in_repl_f3f634_idx',
            old_name='fl_tmsg_irt_idx',
        ),
        migrations.RenameIndex(
            model_name='ticketnote',
            new_name='Frontline_a_ticket__5f1d92_idx',
            old_name='fl_note_ticket_ct_idx',
        ),
    ]
