# Generated by Django 5.2.13 on 2026-05-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0027_merge_20260424_1601'),
        ('Frontline_agent', '0027_workflow_execution_pause'),
    ]

    operations = [
    ]
