# Generated by Django 5.2.13 on 2026-05-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0028_merge_20260429_0005'),
        ('Frontline_agent', '0028_merge_20260501_1508'),
    ]

    operations = [
    ]
