# Generated by Django 5.0.1 on 2026-05-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0028_merge_20260429_0005'),
        ('Frontline_agent', '0028_merge_20260501_1508'),
    ]

    operations = [
    ]
