# Generated by Django 5.2.13 on 2026-05-13 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0028_rename_fl_contact_co_last_idx_frontline_a_company_f5fd63_idx_and_more'),
        ('Frontline_agent', '0029_merge_20260506_2252'),
    ]

    operations = [
    ]
