# Generated by Django 4.2.10 on 2026-05-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0029_merge_20260507_0920'),
        ('Frontline_agent', '0030_merge_20260513_0857'),
        ('Frontline_agent', '0030_merge_20260513_2248'),
    ]

    operations = [
    ]
