# Generated by Django 5.0.1 on 2026-05-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0031_merge_20260516_0125'),
        ('Frontline_agent', '0031_merge_20260521_0030'),
        ('Frontline_agent', '0031_merge_20260521_0934'),
    ]

    operations = [
    ]
