# Generated by Django 5.2.13 on 2026-05-21 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0031_merge_20260521_0934'),
        ('core', '0060_merge_20260521_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontlineAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Verb identifier, e.g. "ticket.status_change", "ticket.assign", "document.delete".', max_length=80)),
                ('target_type', models.CharField(help_text='Model name in lowercase, e.g. "ticket", "document", "notification_template".', max_length=40)),
                ('target_id', models.IntegerField(help_text='PK of the target row. May reference a deleted row — joins must use SET_NULL semantics on the consumer side.')),
                ('diff', models.JSONField(blank=True, default=dict, help_text='{"before": {...}, "after": {...}} | {"created": {...}} | {"deleted": {...}}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='CompanyUser who initiated the action. Null for system / workflow runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_audit_actions', to='core.companyuser')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontline_audit_logs', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='Frontline_a_company_3c288d_idx'), models.Index(fields=['target_type', 'target_id'], name='Frontline_a_target__8393a6_idx'), models.Index(fields=['actor'], name='Frontline_a_actor_i_66d8f6_idx')],
            },
        ),
    ]
