# Generated by Django 5.2.13 on 2026-05-21 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0032_frontline_audit_log'),
        ('core', '0060_merge_20260521_0934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontlineDeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Dotted task name, e.g. "Frontline_agent.tasks.send_notification".', max_length=200)),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task UUID — lets ops cross-reference broker logs.', max_length=64)),
                ('args_json', models.JSONField(blank=True, default=list, help_text='Positional task arguments at the time of failure.')),
                ('kwargs_json', models.JSONField(blank=True, default=dict, help_text='Keyword task arguments at the time of failure.')),
                ('error_type', models.CharField(blank=True, default='', max_length=120)),
                ('error_message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(auto_now_add=True)),
                ('last_failed_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Set by ops when this DLQ entry has been handled (re-run, ignored, etc.).', null=True)),
            ],
            options={
                'ordering': ['-last_failed_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in the picker.', max_length=120)),
                ('body', models.TextField(help_text='The reply text. Plain text, no templating.')),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Bumped each time a macro is inserted, for "most used" sorting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_used', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='URL-safe random token for the public submit endpoint.', max_length=64, unique=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1–5 stars. Null until the recipient submits.', null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the survey email was dispatched.', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='frontlineworkflowexecution',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='frontlineworkflowexecution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('workflow', 'idempotency_key'), name='frontline_workflow_exec_idem_uniq'),
        ),
        migrations.AddField(
            model_name='frontlinedeadletter',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Best-effort — set when the task payload makes the company recoverable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontline_dead_letters', to='core.company'),
        ),
        migrations.AddField(
            model_name='ticketmacro',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontline_ticket_macros', to='core.company'),
        ),
        migrations.AddField(
            model_name='ticketmacro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_macros_created', to='core.companyuser'),
        ),
        migrations.AddField(
            model_name='ticketsatisfaction',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='Frontline_agent.ticket'),
        ),
        migrations.AddIndex(
            model_name='frontlinedeadletter',
            index=models.Index(fields=['task_name', '-last_failed_at'], name='Frontline_a_task_na_40cf84_idx'),
        ),
        migrations.AddIndex(
            model_name='frontlinedeadletter',
            index=models.Index(fields=['company', '-last_failed_at'], name='Frontline_a_company_6a5211_idx'),
        ),
        migrations.AddIndex(
            model_name='frontlinedeadletter',
            index=models.Index(fields=['resolved_at'], name='Frontline_a_resolve_9af1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmacro',
            index=models.Index(fields=['company', 'is_active'], name='Frontline_a_company_d43359_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketmacro',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticketsatisfaction',
            index=models.Index(fields=['submitted_at'], name='Frontline_a_submitt_b5c3ca_idx'),
        ),
    ]
