# Generated by Django 5.2.13 on 2026-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0031_merge_20260521_0030'),
        ('Frontline_agent', '0033_feature_models_macro_dlq_csat_idem'),
    ]

    operations = [
    ]
