# Generated by Django 5.2.13 on 2026-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0034_merge_20260522_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_outdated',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-deprecate: when True, this doc is excluded from retrieval.'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='1-based PDF page this chunk came from. Null for non-PDF docs or PDF chunks that span page breaks.', null=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='quiet_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Optional per-template quiet-hours config. See model source for shape.'),
        ),
    ]
