# Generated by Django 5.2.13 on 2026-05-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0035_page_outdated_quiet_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App'), ('slack', 'Slack (webhook)'), ('teams', 'Microsoft Teams (webhook)')], default='email', max_length=20),
        ),
    ]
