# Generated by Django 5.2.13 on 2026-05-22 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0036_notification_template_slack_teams'),
        ('core', '0069_frontline_channel_webhooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of free-form short labels. Independent of the `category` enum.'),
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Frontline_agent.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_contact_notes_created', to='core.companyuser')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['contact', '-is_pinned', '-created_at'], name='Frontline_a_contact_155aa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('duplicate_of', 'Duplicate of'), ('blocks', 'Blocks'), ('blocked_by', 'Blocked by'), ('related', 'Related to'), ('parent_of', 'Parent of'), ('child_of', 'Child of')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_ticket_links_created', to='core.companyuser')),
                ('from_ticket', models.ForeignKey(help_text='The ticket being annotated.', on_delete=django.db.models.deletion.CASCADE, related_name='linked_to', to='Frontline_agent.ticket')),
                ('to_ticket', models.ForeignKey(help_text='The ticket on the other end of the relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='Frontline_agent.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['from_ticket', 'relation'], name='Frontline_a_from_ti_df6235_idx'), models.Index(fields=['to_ticket', 'relation'], name='Frontline_a_to_tick_f0c51c_idx')],
                'unique_together': {('from_ticket', 'to_ticket', 'relation')},
            },
        ),
    ]
