# Generated by Django 5.0.1 on 2026-05-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0032_merge_20260525_0145'),
        ('Frontline_agent', '0037_tags_links_contact_notes'),
    ]

    operations = [
    ]
