# Generated by Django 4.2.10 on 2026-05-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0031_merge_20260516_0125'),
        ('Frontline_agent', '0037_tags_links_contact_notes'),
    ]

    operations = [
    ]
