# Generated by Django 5.2.13 on 2026-06-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0038_merge_20260526_0153'),
        ('Frontline_agent', '0038_merge_20260530_0056'),
    ]

    operations = [
    ]
