# Generated by Django 4.2.10 on 2026-06-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0039_merge_20260603_0005'),
        ('Frontline_agent', '0039_merge_20260603_0545'),
    ]

    operations = [
    ]
