# Generated by Django 5.0.1 on 2026-06-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0039_merge_20260603_0005'),
        ('Frontline_agent', '0039_merge_20260603_0545'),
    ]

    operations = [
    ]
