# Generated by Django 5.0.1 on 2026-06-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0040_merge_20260604_2320'),
        ('Frontline_agent', '0040_merge_20260609_0307'),
    ]

    operations = [
    ]
