# Generated by Django 5.2.13 on 2026-07-01 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0041_merge_20260613_0010'),
        ('core', '0084_alter_agenttokenquota_next_reset_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBCoverageDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(help_text='Normalised question text used for rollup deduplication.', max_length=120)),
                ('question_display', models.CharField(blank=True, help_text='Original-case question for display; may be longer than the key.', max_length=240)),
                ('reason', models.CharField(blank=True, help_text="Optional short code: 'covered' | 'off_topic' | 'spam' | 'wip' | ''", max_length=32)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('snooze_until', models.DateTimeField(blank=True, help_text='If set and in the past, this dismissal is expired and the gap will reappear on the next report fetch.', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontline_kb_coverage_dismissals', to='core.company')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_kb_dismissals', to='core.companyuser')),
            ],
            options={
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(fields=['company', 'question_key'], name='Frontline_a_company_7a696a_idx'), models.Index(fields=['company', 'snooze_until'], name='Frontline_a_company_848a78_idx')],
                'unique_together': {('company', 'question_key')},
            },
        ),
    ]
