# Generated by Django 4.2.10 on 2026-09-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontline_agent', '0042_kbcoveragedismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, db_index=True, help_text='In-Reply-To header from the incoming email.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, help_text='RFC 5322 Message-ID header. Used for reply threading.', max_length=255),
        ),
    ]
