# Generated by Django 4.2.10 on 2026-10-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_calendarblock_leave_source'),
        ('Frontline_agent', '0046_ticket_document_company_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pm_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontline_tickets', to='core.task'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pm_task_done_noted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
