# Generated by Django 5.0.1 on 2025-12-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email'), ('social', 'Social Media'), ('paid', 'Paid Advertising'), ('partnership', 'Partnership'), ('integrated', 'Integrated')], default='integrated', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('strategy', 'Marketing Strategy'), ('proposal', 'Campaign Proposal'), ('report', 'Performance Report'), ('presentation', 'Presentation'), ('brief', 'Campaign Brief'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('final', 'Final'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='marketing_agent.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Document',
                'verbose_name_plural': 'Marketing Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(choices=[('market_trend', 'Market Trend'), ('competitor', 'Competitor Analysis'), ('customer_behavior', 'Customer Behavior'), ('industry_analysis', 'Industry Analysis'), ('opportunity', 'Opportunity Identification'), ('risk', 'Risk Assessment')], max_length=30)),
                ('topic', models.CharField(max_length=200)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('insights', models.TextField(blank=True)),
                ('source_urls', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_research', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Research',
                'verbose_name_plural': 'Market Research',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_actionable', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.CharField(default='ai_agent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_insights', to='marketing_agent.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_insights', to=settings.AUTH_USER_MODEL)),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_insights', to='marketing_agent.marketresearch')),
            ],
            options={
                'verbose_name': 'Marketing Insight',
                'verbose_name_plural': 'Marketing Insights',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('performance_alert', 'Performance Alert'), ('opportunity', 'Opportunity Alert'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Reached'), ('budget', 'Budget Alert'), ('deadline', 'Deadline Reminder')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_condition', models.JSONField(default=dict)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notification_message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='marketing_agent.campaign')),
                ('recipients', models.ManyToManyField(blank=True, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('channel', models.CharField(blank=True, max_length=50)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='marketing_agent.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Performance',
                'verbose_name_plural': 'Campaign Performance',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['campaign', 'date'], name='marketing_a_campaig_66f805_idx'), models.Index(fields=['metric_name', 'date'], name='marketing_a_metric__2a39bf_idx')],
            },
        ),
    ]
