# Generated by Django 5.0.1 on 2025-12-24 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketinginsight',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='marketinginsight',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='marketinginsight',
            name='research',
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='campaignperformance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketingdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketresearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notificationrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='campaignperformance',
            name='marketing_a_campaig_66f805_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaignperformance',
            name='marketing_a_metric__2a39bf_idx',
        ),
        migrations.AlterUniqueTogether(
            name='campaignperformance',
            unique_together={('campaign', 'metric_name', 'date', 'channel')},
        ),
        migrations.RemoveField(
            model_name='marketingdocument',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='marketresearch',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='notificationrule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='metric_name',
            field=models.CharField(choices=[('impressions', 'Impressions'), ('clicks', 'Clicks'), ('conversions', 'Conversions'), ('engagement', 'Engagement Rate'), ('roi', 'ROI'), ('cac', 'Customer Acquisition Cost'), ('ltv', 'Lifetime Value'), ('revenue', 'Revenue'), ('open_rate', 'Open Rate'), ('click_through_rate', 'Click-Through Rate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='metric_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='campaignperformance',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='marketingdocument',
            name='document_type',
            field=models.CharField(choices=[('strategy', 'Marketing Strategy'), ('proposal', 'Campaign Proposal'), ('report', 'Performance Report'), ('brief', 'Campaign Brief'), ('presentation', 'Presentation'), ('analysis', 'Market Analysis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marketingdocument',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketresearch',
            name='research_type',
            field=models.CharField(choices=[('market_trend', 'Market Trend'), ('competitor', 'Competitor Analysis'), ('customer_behavior', 'Customer Behavior'), ('opportunity', 'Opportunity Analysis'), ('threat', 'Threat Analysis')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='notification_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='rule_type',
            field=models.CharField(choices=[('performance_alert', 'Performance Alert'), ('opportunity', 'Opportunity Alert'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Reached'), ('budget', 'Budget Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='threshold_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='MarketingInsight',
        ),
        migrations.RemoveField(
            model_name='campaignperformance',
            name='metadata',
        ),
    ]
