# Generated by Django 5.0.1 on 2025-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0003_alter_campaign_campaign_type_lead_campaign_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='age_range',
            field=models.CharField(blank=True, help_text='e.g., 25-45', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated interests', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, help_text='Target location/region', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_conversions',
            field=models.IntegerField(blank=True, help_text='Target number of conversions', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_leads',
            field=models.IntegerField(blank=True, help_text='Target number of leads', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target revenue in dollars', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
