# Generated by Django 5.0.1 on 2025-12-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0004_campaign_age_range_campaign_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company_size',
            field=models.CharField(blank=True, help_text='Target company size (e.g., 1-50, 51-200, 201-1000)', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='education',
            field=models.CharField(blank=True, help_text="Target education level (e.g., Bachelor's, Master's)", max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gender',
            field=models.CharField(blank=True, help_text='Target gender (e.g., Male, Female, All)', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='income_level',
            field=models.CharField(blank=True, help_text='Target income level (e.g., $50k-$100k)', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='industry',
            field=models.CharField(blank=True, help_text='Target industry (e.g., Technology, Healthcare)', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(blank=True, help_text='Target language (e.g., English, Spanish)', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_cac',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target Customer Acquisition Cost ($)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_click_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target click-through rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target conversion rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_engagement_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target engagement rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_ltv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target Lifetime Value ($)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_open_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target email open rate (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='timezone',
            field=models.CharField(blank=True, help_text='Target timezone (e.g., EST, PST)', max_length=100),
        ),
    ]
