# Generated by Django 5.0.1 on 2025-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0005_campaign_company_size_campaign_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='education',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='income_level',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_cac',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_click_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_conversion_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_engagement_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_ltv',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_open_rate',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_leads',
            field=models.IntegerField(blank=True, help_text='Target number of leads to achieve (goal - you need to upload leads via CSV)', null=True),
        ),
    ]
