# Generated by Django 5.0.1 on 2025-12-31 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0006_remove_campaign_education_remove_campaign_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_type', models.CharField(choices=[('initial', 'Initial Campaign Email'), ('followup', 'Follow-up Email'), ('test', 'Test Email')], default='initial', max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('html_content', models.TextField(help_text='HTML email content')),
                ('text_content', models.TextField(blank=True, help_text='Plain text version')),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_test_variant', models.CharField(blank=True, choices=[('A', 'Variant A'), ('B', 'Variant B')], help_text='A or B variant for A/B testing', max_length=1)),
                ('followup_sequence_number', models.IntegerField(default=0, help_text='Sequence number for follow-up emails (0 = initial, 1 = first follow-up, etc.)')),
                ('followup_delay_days', models.IntegerField(default=3, help_text='Days to wait before sending this follow-up')),
                ('spam_score', models.DecimalField(blank=True, decimal_places=2, help_text='Spam score (0-100, lower is better)', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='marketing_agent.campaign')),
            ],
            options={
                'ordering': ['campaign', 'followup_sequence_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounce_reason', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_test_variant', models.CharField(blank=True, max_length=1)),
                ('is_followup', models.BooleanField(default=False)),
                ('followup_sequence_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sends', to='marketing_agent.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_history', to='marketing_agent.lead')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='marketing_agent.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='marketing_a_campaig_508f24_idx'), models.Index(fields=['lead', 'campaign'], name='marketing_a_lead_id_98779b_idx')],
            },
        ),
    ]
