# Generated by Django 5.0.1 on 2025-12-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0007_emailtemplate_emailsendhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_ab_test',
            field=models.BooleanField(default=False, help_text='Is this part of an A/B test?'),
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sequence (e.g., "Welcome Series", "Product Launch")', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to='marketing_agent.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(help_text='Order in sequence (1, 2, 3...)')),
                ('delay_days', models.IntegerField(default=0, help_text='Days to wait after previous step before sending this')),
                ('delay_hours', models.IntegerField(default=0, help_text='Hours to wait after previous step before sending this')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='marketing_agent.emailsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_steps', to='marketing_agent.emailtemplate')),
            ],
            options={
                'ordering': ['sequence', 'step_order'],
                'unique_together': {('sequence', 'step_order')},
            },
        ),
    ]
