# Generated by Django 5.0.1 on 2025-12-31 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0008_add_email_sequence_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this account (e.g., "Main Gmail Account")', max_length=200)),
                ('account_type', models.CharField(choices=[('gmail', 'Gmail'), ('smtp', 'SMTP Server'), ('hostinger', 'Hostinger'), ('outlook', 'Outlook'), ('custom', 'Custom SMTP')], default='smtp', max_length=20)),
                ('email', models.EmailField(help_text='Email address used for sending', max_length=254)),
                ('smtp_host', models.CharField(help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)')),
                ('smtp_username', models.CharField(help_text='SMTP username (usually same as email)', max_length=255)),
                ('smtp_password', models.CharField(help_text='SMTP password or app password', max_length=500)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('is_gmail_app_password', models.BooleanField(default=False, help_text='Is this using Gmail App Password?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this account active and ready to use?')),
                ('is_default', models.BooleanField(default=False, help_text='Use this as default account for sending')),
                ('last_tested_at', models.DateTimeField(blank=True, help_text='Last time account was tested', null=True)),
                ('test_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('not_tested', 'Not Tested')], default='not_tested', max_length=20)),
                ('test_error', models.TextField(blank=True, help_text='Error message from last test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-is_active', '-created_at'],
                'unique_together': {('email', 'owner')},
            },
        ),
    ]
