# Generated by Django 5.0.1 on 2025-12-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0009_add_email_account_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsendhistory',
            name='tracking_token',
            field=models.CharField(blank=True, help_text='Unique token for email tracking (opens/clicks)', max_length=64, null=True, unique=True),
        ),
    ]
