# Generated by Django 5.0.1 on 2026-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0010_emailsendhistory_tracking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsequencestep',
            name='delay_minutes',
            field=models.IntegerField(default=0, help_text='Minutes to wait after previous step before sending this'),
        ),
    ]
