# Generated by Django 5.0.1 on 2026-01-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0011_add_delay_minutes_to_sequence_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsequence',
            name='email_account',
            field=models.ForeignKey(blank=True, help_text='Email account to use for sending sequence emails', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='marketing_agent.emailaccount'),
        ),
    ]
