# Generated by Django 5.0.1 on 2026-01-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0012_add_email_account_to_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=0, help_text='Current step number in sequence (0 = not started, 1 = first step, etc.)')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='When the last email in sequence was sent', null=True)),
                ('replied', models.BooleanField(default=False, help_text='Has this contact replied? (stops automation)')),
                ('completed', models.BooleanField(default=False, help_text='Has this contact completed the sequence?')),
                ('replied_at', models.DateTimeField(blank=True, help_text='When the contact replied', null=True)),
                ('reply_subject', models.CharField(blank=True, help_text='Subject of the reply email', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, help_text='When sequence started for this contact', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sequence completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='marketing_agent.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='marketing_agent.lead')),
                ('sequence', models.ForeignKey(blank=True, help_text='Current sequence this contact is in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='marketing_agent.emailsequence')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'completed', 'replied'], name='marketing_a_campaig_c04f71_idx'), models.Index(fields=['campaign', 'sequence', 'current_step'], name='marketing_a_campaig_e50d08_idx'), models.Index(fields=['last_sent_at'], name='marketing_a_last_se_c66ef9_idx')],
                'unique_together': {('campaign', 'lead')},
            },
        ),
    ]
