# Generated by Django 5.0.1 on 2026-01-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0014_campaigncontact_per_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('performance_alert', 'Performance Alert'), ('opportunity', 'Opportunity Alert'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Reached'), ('budget', 'Budget Alert'), ('campaign_status', 'Campaign Status Change'), ('email_delivery', 'Email Delivery Issue'), ('engagement', 'Engagement Alert')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketing_agent.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='marketing_a_user_id_5d1e24_idx'), models.Index(fields=['campaign', 'notification_type'], name='marketing_a_campaig_32bdea_idx'), models.Index(fields=['created_at'], name='marketing_a_created_a2d8cb_idx')],
            },
        ),
    ]
