# Generated by Django 5.0.1 on 2026-01-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0015_marketingnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='reply_analysis',
            field=models.TextField(blank=True, help_text='AI analysis of the reply sentiment and interest'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='reply_content',
            field=models.TextField(blank=True, help_text='Full content of the reply email'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='reply_interest_level',
            field=models.CharField(choices=[('positive', 'Positive/Interested'), ('negative', 'Negative/Not Interested'), ('neutral', 'Neutral'), ('not_analyzed', 'Not Analyzed')], default='not_analyzed', help_text='AI-determined interest level based on reply content', max_length=20),
        ),
    ]
