# Generated by Django 5.0.1 on 2026-01-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0016_add_reply_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncontact',
            name='sub_sequence',
            field=models.ForeignKey(blank=True, help_text='Sub-sequence this contact is in (triggered by reply)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sequence_contacts', to='marketing_agent.emailsequence'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='sub_sequence_completed',
            field=models.BooleanField(default=False, help_text='Has this contact completed the sub-sequence?'),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='sub_sequence_last_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last sub-sequence email was sent', null=True),
        ),
        migrations.AddField(
            model_name='campaigncontact',
            name='sub_sequence_step',
            field=models.IntegerField(default=0, help_text='Current step in sub-sequence (0 = not started)'),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='is_sub_sequence',
            field=models.BooleanField(default=False, help_text='Is this a sub-sequence (triggered by replies)?'),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='parent_sequence',
            field=models.ForeignKey(blank=True, help_text='Parent sequence (if this is a sub-sequence triggered by replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequences', to='marketing_agent.emailsequence'),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='replied',
            field=models.BooleanField(default=False, help_text='Has this contact replied? (stops main sequence, starts sub-sequence)'),
        ),
        migrations.AlterField(
            model_name='campaigncontact',
            name='sequence',
            field=models.ForeignKey(blank=True, help_text='Main sequence this contact is in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='marketing_agent.emailsequence'),
        ),
    ]
