# Generated by Django 5.0.1 on 2026-01-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0017_add_sub_sequence_support'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaigncontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emailsequence',
            name='interest_level',
            field=models.CharField(choices=[('any', 'Any Reply (Default)'), ('positive', 'Interested / Positive'), ('negative', 'Not Interested / Negative'), ('neutral', 'Neutral / Acknowledgment'), ('requested_info', 'Requested More Information'), ('objection', 'Has Objection / Concern'), ('unsubscribe', 'Unsubscribe Request')], default='any', help_text='Interest level this sub-sequence handles (only for sub-sequences)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['campaign', 'sub_sequence', 'sub_sequence_step'], name='marketing_a_campaig_dd5d41_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['sub_sequence_last_sent_at'], name='marketing_a_sub_seq_223ee7_idx'),
        ),
    ]
