# Generated by Django 5.0.1 on 2026-01-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0020_reply_sequence_reply_sub_sequence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='enable_imap_sync',
            field=models.BooleanField(default=False, help_text='Enable automatic IMAP sync for reply detection'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_host',
            field=models.CharField(blank=True, help_text='IMAP server host (e.g., imap.hostinger.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_password',
            field=models.CharField(blank=True, help_text='IMAP password', max_length=500),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_port',
            field=models.IntegerField(blank=True, help_text='IMAP server port (993 for SSL, 143 for TLS)', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL for IMAP connection'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='imap_username',
            field=models.CharField(blank=True, help_text='IMAP username (usually same as email)', max_length=255),
        ),
        migrations.AddField(
            model_name='emailsendhistory',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Email Message-ID header for reply detection', max_length=500, null=True),
        ),
    ]
