# Generated by Django 5.0.1 on 2026-01-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0025_remove_regexp_like_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaigncontact',
            new_name='ppp_marketi_campaig_2b624b_idx',
            old_name='marketing_a_campaig_c04f71_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigncontact',
            new_name='ppp_marketi_campaig_ee2d67_idx',
            old_name='marketing_a_campaig_e50d08_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigncontact',
            new_name='ppp_marketi_campaig_d8934a_idx',
            old_name='marketing_a_campaig_dd5d41_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigncontact',
            new_name='ppp_marketi_last_se_4c3b6d_idx',
            old_name='marketing_a_last_se_c66ef9_idx',
        ),
        migrations.RenameIndex(
            model_name='campaigncontact',
            new_name='ppp_marketi_sub_seq_9a212b_idx',
            old_name='marketing_a_sub_seq_223ee7_idx',
        ),
        migrations.RenameIndex(
            model_name='emailsendhistory',
            new_name='ppp_marketi_campaig_d260ea_idx',
            old_name='marketing_a_campaig_508f24_idx',
        ),
        migrations.RenameIndex(
            model_name='emailsendhistory',
            new_name='ppp_marketi_lead_id_f8daad_idx',
            old_name='marketing_a_lead_id_98779b_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingnotification',
            new_name='ppp_marketi_user_id_109fb5_idx',
            old_name='marketing_a_user_id_5d1e24_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingnotification',
            new_name='ppp_marketi_campaig_524fe1_idx',
            old_name='marketing_a_campaig_32bdea_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingnotification',
            new_name='ppp_marketi_created_ecef0c_idx',
            old_name='marketing_a_created_a2d8cb_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='ppp_marketi_contact_ffbe1b_idx',
            old_name='marketing_a_contact_1e9b29_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='ppp_marketi_campaig_bd195b_idx',
            old_name='marketing_a_campaig_75326a_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='ppp_marketi_lead_id_e023e4_idx',
            old_name='marketing_a_lead_id_cbaaf3_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='ppp_marketi_sequenc_a9129b_idx',
            old_name='marketing_a_sequenc_f2638b_idx',
        ),
        migrations.RenameIndex(
            model_name='reply',
            new_name='ppp_marketi_campaig_ce4be4_idx',
            old_name='marketing_a_campaig_b0ae7b_idx',
        ),
        migrations.AlterField(
            model_name='marketingnotification',
            name='notification_type',
            field=models.CharField(choices=[('performance_alert', 'Performance Alert'), ('opportunity', 'Opportunity Alert'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Reached'), ('campaign_status', 'Campaign Status Change'), ('email_delivery', 'Email Delivery Issue'), ('engagement', 'Engagement Alert')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='rule_type',
            field=models.CharField(choices=[('performance_alert', 'Performance Alert'), ('opportunity', 'Opportunity Alert'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Reached')], max_length=20),
        ),
    ]
