# Generated by Django 4.2.7 on 2026-02-26 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0027_savedgraphprompt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedgraphprompt',
            new_name='ppp_marketi_created_3d34be_idx',
            old_name='ppp_marketi_created_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='savedgraphprompt',
            new_name='ppp_marketi_created_b18f3c_idx',
            old_name='ppp_marketi_created_9b2c3d_idx',
        ),
        migrations.AlterField(
            model_name='savedgraphprompt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
