# Generated by Django 5.0.1 on 2026-03-03 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0027_savedgraphprompt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savedgraphprompt',
            new_name='ppp_marketi_created_3d34be_idx',
            old_name='ppp_marketi_created_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='savedgraphprompt',
            new_name='ppp_marketi_created_b18f3c_idx',
            old_name='ppp_marketi_created_9b2c3d_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedgraphprompt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
