# Generated by Django 5.0.1 on 2026-03-12 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_frontline_widget_key'),
        ('marketing_agent', '0028_rename_ppp_marketi_created_8a1b2c_idx_ppp_marketi_created_3d34be_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketingQAChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', help_text='Chat title (e.g. first question snippet)', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(help_text='Company user who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_qa_chats', to='core.companyuser')),
            ],
            options={
                'db_table': 'ppp_marketingagent_marketingqachat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingQAChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('response_data', models.JSONField(blank=True, help_text='For assistant: full API response { answer, insights }', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketing_agent.marketingqachat')),
            ],
            options={
                'db_table': 'ppp_marketingagent_marketingqachatmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketResearchChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chat', help_text='Chat title (e.g. first topic snippet)', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_user', models.ForeignKey(help_text='Company user who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='marketing_research_chats', to='core.companyuser')),
            ],
            options={
                'db_table': 'ppp_marketingagent_marketresearchchat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketResearchChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('response_data', models.JSONField(blank=True, help_text='For assistant: full API response', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(help_text='Chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketing_agent.marketresearchchat')),
            ],
            options={
                'db_table': 'ppp_marketingagent_marketresearchchatmessage',
                'ordering': ['created_at'],
            },
        ),
    ]
