# Generated by Django 4.2.10 on 2026-04-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0029_add_qa_research_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='imap_sync_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days of mail to pull on each IMAP sync. Used by the Reply Draft Agent inbox view.'),
        ),
    ]
