# Generated by Django 4.2.10 on 2026-05-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0033_unique_reply_agent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='is_reply_agent_account',
            field=models.BooleanField(default=False, help_text='Designates this account as the Reply Draft Agent inbox source (one per owner). Compatible with marketing campaign use on the same row.'),
        ),
    ]
