# Generated by Django 4.2.10 on 2026-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0035_emailaccount_is_marketing_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='last_sync_completed_at',
            field=models.DateTimeField(blank=True, help_text='Wall-clock time the most recent successful sync finished.', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='last_sync_stage',
            field=models.PositiveIntegerField(default=0, help_text='Window (in days) of the latest staged-sync phase: 0=idle, 30/60/90 once each phase finishes.'),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='sync_in_progress',
            field=models.BooleanField(default=False, help_text='True while a sync is actively running for this account.'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='is_reply_agent_account',
            field=models.BooleanField(default=False, help_text='Designates this account as the Reply Draft Agent inbox source (one per owner). Independent of is_marketing_account; both can be True for dual-use.'),
        ),
    ]
