# Generated by Django 4.2.10 on 2026-07-20 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0036_emailaccount_sync_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplySubSequenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_level', models.CharField(default='any', max_length=20)),
                ('step', models.IntegerField(default=0, help_text='Current step (0 = not started).')),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='When the last step went out (delay anchor).', null=True)),
                ('completed', models.BooleanField(default=False, help_text='All steps sent.')),
                ('cancelled', models.BooleanField(default=False, help_text='Run stopped early (e.g. lead replied to the sub-seq itself).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequence_runs', to='marketing_agent.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequence_runs', to='marketing_agent.campaigncontact')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequence_runs', to='marketing_agent.lead')),
                ('reply', models.OneToOneField(help_text='The reply that triggered this sub-sequence run.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequence_run', to='marketing_agent.reply')),
                ('sub_sequence', models.ForeignKey(help_text='The sub-sequence being sent for this reply.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_sequence_runs', to='marketing_agent.emailsequence')),
            ],
            options={
                'db_table': 'ppp_marketingagent_reply_subseq_run',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['campaign', 'completed', 'cancelled'], name='ppp_marketi_campaig_86efbd_idx'), models.Index(fields=['lead', 'created_at'], name='ppp_marketi_lead_id_0b65f7_idx')],
            },
        ),
    ]
