# Generated by Django 4.2.10 on 2026-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_agent', '0037_replysubsequencerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='imap_sync_email_limit',
            field=models.PositiveIntegerField(default=200, help_text='Max emails to fetch per folder sweep on each IMAP sync (50 / 100 / 200).'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='imap_sync_days',
            field=models.PositiveIntegerField(default=90, help_text='How many days of mail to pull on each IMAP sync. Used by the Reply Draft Agent inbox view. One of 30 / 60 / 90.'),
        ),
    ]
